// Package asciiban Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2023-08-16 15:10:18.181222 +1000 AEST m=+1.687057751
// using data from https://github.com/xero/figlet-fonts

//go:build !exclude

package asciiban

import (
	_ "embed"
	"fmt"
	"strings"
)

//go:embed fontpack/amc3line.txt.gz
var FontAMC3Line string

//go:embed fontpack/amc3liv1.txt.gz
var FontAMC3Liv1 string

//go:embed fontpack/amcaaa01.txt.gz
var FontAMCAAA01 string

//go:embed fontpack/amcneko.txt.gz
var FontAMCNeko string

//go:embed fontpack/amcrazor.txt.gz
var FontAMCRazor string

//go:embed fontpack/amcrazor2.txt.gz
var FontAMCRazor2 string

//go:embed fontpack/amcslash.txt.gz
var FontAMCSlash string

//go:embed fontpack/amcslider.txt.gz
var FontAMCSlider string

//go:embed fontpack/amcthin.txt.gz
var FontAMCThin string

//go:embed fontpack/amctubes.txt.gz
var FontAMCTubes string

//go:embed fontpack/amcuntitled.txt.gz
var FontAMCUntitled string

//go:embed fontpack/ansiregular.txt.gz
var FontANSIRegular string

//go:embed fontpack/ansishadow.txt.gz
var FontANSIShadow string

//go:embed fontpack/asciinewroman.txt.gz
var FontASCIINewRoman string

//go:embed fontpack/acrobatic.txt.gz
var FontAcrobatic string

//go:embed fontpack/alligator.txt.gz
var FontAlligator string

//go:embed fontpack/alligator2.txt.gz
var FontAlligator2 string

//go:embed fontpack/alligator3.txt.gz
var FontAlligator3 string

//go:embed fontpack/alpha.txt.gz
var FontAlpha string

//go:embed fontpack/alphabet.txt.gz
var FontAlphabet string

//go:embed fontpack/amcrazo2.txt.gz
var FontAmcrazo2 string

//go:embed fontpack/amcslder.txt.gz
var FontAmcslder string

//go:embed fontpack/amcun1.txt.gz
var FontAmcun1 string

//go:embed fontpack/arrows.txt.gz
var FontArrows string

//go:embed fontpack/avatar.txt.gz
var FontAvatar string

//go:embed fontpack/b1ff.txt.gz
var FontB1FF string

//go:embed fontpack/banner.txt.gz
var FontBanner string

//go:embed fontpack/banner3.txt.gz
var FontBanner3 string

//go:embed fontpack/banner3d.txt.gz
var FontBanner3D string

//go:embed fontpack/banner4.txt.gz
var FontBanner4 string

//go:embed fontpack/barbwire.txt.gz
var FontBarbwire string

//go:embed fontpack/basic.txt.gz
var FontBasic string

//go:embed fontpack/bear.txt.gz
var FontBear string

//go:embed fontpack/bell.txt.gz
var FontBell string

//go:embed fontpack/benjamin.txt.gz
var FontBenjamin string

//go:embed fontpack/big.txt.gz
var FontBig string

//go:embed fontpack/bigchief.txt.gz
var FontBigChief string

//go:embed fontpack/bigmoneyne.txt.gz
var FontBigMoneyne string

//go:embed fontpack/bigmoneynw.txt.gz
var FontBigMoneynw string

//go:embed fontpack/bigmoneyse.txt.gz
var FontBigMoneyse string

//go:embed fontpack/bigmoneysw.txt.gz
var FontBigMoneysw string

//go:embed fontpack/bigfig.txt.gz
var FontBigfig string

//go:embed fontpack/binary.txt.gz
var FontBinary string

//go:embed fontpack/block.txt.gz
var FontBlock string

//go:embed fontpack/blocks.txt.gz
var FontBlocks string

//go:embed fontpack/bloody.txt.gz
var FontBloody string

//go:embed fontpack/bolger.txt.gz
var FontBolger string

//go:embed fontpack/braced.txt.gz
var FontBraced string

//go:embed fontpack/bright.txt.gz
var FontBright string

//go:embed fontpack/broadway.txt.gz
var FontBroadway string

//go:embed fontpack/broadwaykb.txt.gz
var FontBroadwayKB string

//go:embed fontpack/bubble.txt.gz
var FontBubble string

//go:embed fontpack/bulbhead.txt.gz
var FontBulbhead string

//go:embed fontpack/calgphy2.txt.gz
var FontCalgphy2 string

//go:embed fontpack/caligraphy.txt.gz
var FontCaligraphy string

//go:embed fontpack/caligraphy2.txt.gz
var FontCaligraphy2 string

//go:embed fontpack/calvins.txt.gz
var FontCalvinS string

//go:embed fontpack/catwalk.txt.gz
var FontCatwalk string

//go:embed fontpack/chiseled.txt.gz
var FontChiseled string

//go:embed fontpack/chunky.txt.gz
var FontChunky string

//go:embed fontpack/coinstak.txt.gz
var FontCoinstak string

//go:embed fontpack/cola.txt.gz
var FontCola string

//go:embed fontpack/colossal.txt.gz
var FontColossal string

//go:embed fontpack/computer.txt.gz
var FontComputer string

//go:embed fontpack/contessa.txt.gz
var FontContessa string

//go:embed fontpack/contrast.txt.gz
var FontContrast string

//go:embed fontpack/cosmic.txt.gz
var FontCosmic string

//go:embed fontpack/cosmike.txt.gz
var FontCosmike string

//go:embed fontpack/crawford.txt.gz
var FontCrawford string

//go:embed fontpack/crawford2.txt.gz
var FontCrawford2 string

//go:embed fontpack/crazy.txt.gz
var FontCrazy string

//go:embed fontpack/cricket.txt.gz
var FontCricket string

//go:embed fontpack/cursive.txt.gz
var FontCursive string

//go:embed fontpack/cyberlarge.txt.gz
var FontCyberlarge string

//go:embed fontpack/cybermedium.txt.gz
var FontCybermedium string

//go:embed fontpack/cybersmall.txt.gz
var FontCybersmall string

//go:embed fontpack/cygnet.txt.gz
var FontCygnet string

//go:embed fontpack/danc4.txt.gz
var FontDANC4 string

//go:embed fontpack/dosrebel.txt.gz
var FontDOSRebel string

//go:embed fontpack/dwhistled.txt.gz
var FontDWhistled string

//go:embed fontpack/dancingfont.txt.gz
var FontDancingFont string

//go:embed fontpack/decimal.txt.gz
var FontDecimal string

//go:embed fontpack/defleppard.txt.gz
var FontDefLeppard string

//go:embed fontpack/deltacorpspriest1.txt.gz
var FontDeltaCorpsPriest1 string

//go:embed fontpack/diamond.txt.gz
var FontDiamond string

//go:embed fontpack/dietcola.txt.gz
var FontDietCola string

//go:embed fontpack/digital.txt.gz
var FontDigital string

//go:embed fontpack/doh.txt.gz
var FontDoh string

//go:embed fontpack/doom.txt.gz
var FontDoom string

//go:embed fontpack/dotmatrix.txt.gz
var FontDotMatrix string

//go:embed fontpack/double.txt.gz
var FontDouble string

//go:embed fontpack/doubleshorts.txt.gz
var FontDoubleShorts string

//go:embed fontpack/drpepper.txt.gz
var FontDrPepper string

//go:embed fontpack/eftichess.txt.gz
var FontEftiChess string

//go:embed fontpack/eftifont.txt.gz
var FontEftiFont string

//go:embed fontpack/eftiitalic.txt.gz
var FontEftiItalic string

//go:embed fontpack/eftipiti.txt.gz
var FontEftiPiti string

//go:embed fontpack/eftirobot.txt.gz
var FontEftiRobot string

//go:embed fontpack/eftiwall.txt.gz
var FontEftiWall string

//go:embed fontpack/eftiwater.txt.gz
var FontEftiWater string

//go:embed fontpack/eftitalic.txt.gz
var FontEftitalic string

//go:embed fontpack/electronic.txt.gz
var FontElectronic string

//go:embed fontpack/elite.txt.gz
var FontElite string

//go:embed fontpack/epic.txt.gz
var FontEpic string

//go:embed fontpack/f1row.txt.gz
var FontF1Row string

//go:embed fontpack/f3d.txt.gz
var FontF3D string

//go:embed fontpack/f3dascii.txt.gz
var FontF3DASCII string

//go:embed fontpack/f3ddiagonal.txt.gz
var FontF3DDiagonal string

//go:embed fontpack/f3x5.txt.gz
var FontF3x5 string

//go:embed fontpack/f4max.txt.gz
var FontF4Max string

//go:embed fontpack/f5lineoblique.txt.gz
var FontF5LineOblique string

//go:embed fontpack/fender.txt.gz
var FontFender string

//go:embed fontpack/filter.txt.gz
var FontFilter string

//go:embed fontpack/firefontk.txt.gz
var FontFireFontk string

//go:embed fontpack/firefonts.txt.gz
var FontFireFonts string

//go:embed fontpack/flipped.txt.gz
var FontFlipped string

//go:embed fontpack/flowerpower.txt.gz
var FontFlowerPower string

//go:embed fontpack/fourtops.txt.gz
var FontFourTops string

//go:embed fontpack/funface.txt.gz
var FontFunFace string

//go:embed fontpack/funfaces.txt.gz
var FontFunFaces string

//go:embed fontpack/fuzzy.txt.gz
var FontFuzzy string

//go:embed fontpack/georgi16.txt.gz
var FontGeorgi16 string

//go:embed fontpack/georgia11.txt.gz
var FontGeorgia11 string

//go:embed fontpack/ghost.txt.gz
var FontGhost string

//go:embed fontpack/ghoulish.txt.gz
var FontGhoulish string

//go:embed fontpack/glenyn.txt.gz
var FontGlenyn string

//go:embed fontpack/goofy.txt.gz
var FontGoofy string

//go:embed fontpack/gothic.txt.gz
var FontGothic string

//go:embed fontpack/graceful.txt.gz
var FontGraceful string

//go:embed fontpack/gradient.txt.gz
var FontGradient string

//go:embed fontpack/graffiti.txt.gz
var FontGraffiti string

//go:embed fontpack/greek.txt.gz
var FontGreek string

//go:embed fontpack/halfiwi.txt.gz
var FontHalfiwi string

//go:embed fontpack/henry3d.txt.gz
var FontHenry3D string

//go:embed fontpack/hex.txt.gz
var FontHex string

//go:embed fontpack/hieroglyphs.txt.gz
var FontHieroglyphs string

//go:embed fontpack/hollywood.txt.gz
var FontHollywood string

//go:embed fontpack/horizontalleft.txt.gz
var FontHorizontalLeft string

//go:embed fontpack/horizontalright.txt.gz
var FontHorizontalRight string

//go:embed fontpack/icl1900.txt.gz
var FontICL1900 string

//go:embed fontpack/impossible.txt.gz
var FontImpossible string

//go:embed fontpack/invita.txt.gz
var FontInvita string

//go:embed fontpack/isometric1.txt.gz
var FontIsometric1 string

//go:embed fontpack/isometric2.txt.gz
var FontIsometric2 string

//go:embed fontpack/isometric3.txt.gz
var FontIsometric3 string

//go:embed fontpack/isometric4.txt.gz
var FontIsometric4 string

//go:embed fontpack/italic.txt.gz
var FontItalic string

//go:embed fontpack/ivrit.txt.gz
var FontIvrit string

//go:embed fontpack/jsblockletters.txt.gz
var FontJSBlockLetters string

//go:embed fontpack/jsbracketletters.txt.gz
var FontJSBracketLetters string

//go:embed fontpack/jscapitalcurves.txt.gz
var FontJSCapitalCurves string

//go:embed fontpack/jscursive.txt.gz
var FontJSCursive string

//go:embed fontpack/jsstickletters.txt.gz
var FontJSStickLetters string

//go:embed fontpack/jacky.txt.gz
var FontJacky string

//go:embed fontpack/jazmine.txt.gz
var FontJazmine string

//go:embed fontpack/jerusalem.txt.gz
var FontJerusalem string

//go:embed fontpack/katakana.txt.gz
var FontKatakana string

//go:embed fontpack/kban.txt.gz
var FontKban string

//go:embed fontpack/keyboard.txt.gz
var FontKeyboard string

//go:embed fontpack/knob.txt.gz
var FontKnob string

//go:embed fontpack/konto.txt.gz
var FontKonto string

//go:embed fontpack/kontoslant.txt.gz
var FontKontoSlant string

//go:embed fontpack/lcd.txt.gz
var FontLCD string

//go:embed fontpack/larry3d.txt.gz
var FontLarry3D string

//go:embed fontpack/larry3d2.txt.gz
var FontLarry3D2 string

//go:embed fontpack/lean.txt.gz
var FontLean string

//go:embed fontpack/letters.txt.gz
var FontLetters string

//go:embed fontpack/lildevil.txt.gz
var FontLilDevil string

//go:embed fontpack/lineblocks.txt.gz
var FontLineBlocks string

//go:embed fontpack/linux.txt.gz
var FontLinux string

//go:embed fontpack/lockergnome.txt.gz
var FontLockergnome string

//go:embed fontpack/madrid.txt.gz
var FontMadrid string

//go:embed fontpack/marquee.txt.gz
var FontMarquee string

//go:embed fontpack/maxfour.txt.gz
var FontMaxfour string

//go:embed fontpack/merlin1.txt.gz
var FontMerlin1 string

//go:embed fontpack/merlin2.txt.gz
var FontMerlin2 string

//go:embed fontpack/mike.txt.gz
var FontMike string

//go:embed fontpack/mini.txt.gz
var FontMini string

//go:embed fontpack/mirror.txt.gz
var FontMirror string

//go:embed fontpack/mnemonic.txt.gz
var FontMnemonic string

//go:embed fontpack/modular.txt.gz
var FontModular string

//go:embed fontpack/morse.txt.gz
var FontMorse string

//go:embed fontpack/morse2.txt.gz
var FontMorse2 string

//go:embed fontpack/moscow.txt.gz
var FontMoscow string

//go:embed fontpack/mshebrew210.txt.gz
var FontMshebrew210 string

//go:embed fontpack/muzzle.txt.gz
var FontMuzzle string

//go:embed fontpack/nscript.txt.gz
var FontNScript string

//go:embed fontpack/ntgreek.txt.gz
var FontNTGreek string

//go:embed fontpack/nvscript.txt.gz
var FontNVScript string

//go:embed fontpack/nancyj.txt.gz
var FontNancyj string

//go:embed fontpack/nancyjfancy.txt.gz
var FontNancyjFancy string

//go:embed fontpack/nancyjimproved.txt.gz
var FontNancyjImproved string

//go:embed fontpack/nancyjunderlined.txt.gz
var FontNancyjUnderlined string

//go:embed fontpack/nipples.txt.gz
var FontNipples string

//go:embed fontpack/o8.txt.gz
var FontO8 string

//go:embed fontpack/os2.txt.gz
var FontOS2 string

//go:embed fontpack/octal.txt.gz
var FontOctal string

//go:embed fontpack/ogre.txt.gz
var FontOgre string

//go:embed fontpack/oldbanner.txt.gz
var FontOldBanner string

//go:embed fontpack/patorjkhex.txt.gz
var FontPatorjkHeX string

//go:embed fontpack/patorjkscheese.txt.gz
var FontPatorjksCheese string

//go:embed fontpack/pawp.txt.gz
var FontPawp string

//go:embed fontpack/peaks.txt.gz
var FontPeaks string

//go:embed fontpack/peaksslant.txt.gz
var FontPeaksSlant string

//go:embed fontpack/pebbles.txt.gz
var FontPebbles string

//go:embed fontpack/pepper.txt.gz
var FontPepper string

//go:embed fontpack/poison.txt.gz
var FontPoison string

//go:embed fontpack/puffy.txt.gz
var FontPuffy string

//go:embed fontpack/puzzle.txt.gz
var FontPuzzle string

//go:embed fontpack/pyramid.txt.gz
var FontPyramid string

//go:embed fontpack/rammstein.txt.gz
var FontRammstein string

//go:embed fontpack/rectangles.txt.gz
var FontRectangles string

//go:embed fontpack/redphoenix.txt.gz
var FontRedPhoenix string

//go:embed fontpack/relief.txt.gz
var FontRelief string

//go:embed fontpack/relief2.txt.gz
var FontRelief2 string

//go:embed fontpack/rev.txt.gz
var FontRev string

//go:embed fontpack/reverse.txt.gz
var FontReverse string

//go:embed fontpack/roman.txt.gz
var FontRoman string

//go:embed fontpack/rot13.txt.gz
var FontRot13 string

//go:embed fontpack/rotated.txt.gz
var FontRotated string

//go:embed fontpack/rounded.txt.gz
var FontRounded string

//go:embed fontpack/rowancap.txt.gz
var FontRowanCap string

//go:embed fontpack/rozzo.txt.gz
var FontRozzo string

//go:embed fontpack/runic.txt.gz
var FontRunic string

//go:embed fontpack/runyc.txt.gz
var FontRunyc string

//go:embed fontpack/sblood.txt.gz
var FontSBlood string

//go:embed fontpack/slscript.txt.gz
var FontSLScript string

//go:embed fontpack/santaclara.txt.gz
var FontSantaClara string

//go:embed fontpack/script.txt.gz
var FontScript string

//go:embed fontpack/serifcap.txt.gz
var FontSerifcap string

//go:embed fontpack/shadow.txt.gz
var FontShadow string

//go:embed fontpack/shimrod.txt.gz
var FontShimrod string

//go:embed fontpack/short.txt.gz
var FontShort string

//go:embed fontpack/slant.txt.gz
var FontSlant string

//go:embed fontpack/slantrelief.txt.gz
var FontSlantRelief string

//go:embed fontpack/slide.txt.gz
var FontSlide string

//go:embed fontpack/small.txt.gz
var FontSmall string

//go:embed fontpack/smallcaps.txt.gz
var FontSmallCaps string

//go:embed fontpack/smallisometric1.txt.gz
var FontSmallIsometric1 string

//go:embed fontpack/smallkeyboard.txt.gz
var FontSmallKeyboard string

//go:embed fontpack/smallpoison.txt.gz
var FontSmallPoison string

//go:embed fontpack/smallscript.txt.gz
var FontSmallScript string

//go:embed fontpack/smallshadow.txt.gz
var FontSmallShadow string

//go:embed fontpack/smallslant.txt.gz
var FontSmallSlant string

//go:embed fontpack/smalltengwar.txt.gz
var FontSmallTengwar string

//go:embed fontpack/smisome1.txt.gz
var FontSmisome1 string

//go:embed fontpack/smkeyboard.txt.gz
var FontSmkeyboard string

//go:embed fontpack/smpoison.txt.gz
var FontSmpoison string

//go:embed fontpack/smscript.txt.gz
var FontSmscript string

//go:embed fontpack/smshadow.txt.gz
var FontSmshadow string

//go:embed fontpack/smslant.txt.gz
var FontSmslant string

//go:embed fontpack/smtengwar.txt.gz
var FontSmtengwar string

//go:embed fontpack/soft.txt.gz
var FontSoft string

//go:embed fontpack/speed.txt.gz
var FontSpeed string

//go:embed fontpack/spliff.txt.gz
var FontSpliff string

//go:embed fontpack/srelief.txt.gz
var FontSrelief string

//go:embed fontpack/stacey.txt.gz
var FontStacey string

//go:embed fontpack/stampate.txt.gz
var FontStampate string

//go:embed fontpack/stampatello.txt.gz
var FontStampatello string

//go:embed fontpack/standard.txt.gz
var FontStandard string

//go:embed fontpack/starstrips.txt.gz
var FontStarStrips string

//go:embed fontpack/starwars.txt.gz
var FontStarWars string

//go:embed fontpack/stellar.txt.gz
var FontStellar string

//go:embed fontpack/stforek.txt.gz
var FontStforek string

//go:embed fontpack/stickletters.txt.gz
var FontStickLetters string

//go:embed fontpack/stop.txt.gz
var FontStop string

//go:embed fontpack/straight.txt.gz
var FontStraight string

//go:embed fontpack/strongerthanall.txt.gz
var FontStrongerThanAll string

//go:embed fontpack/subzero.txt.gz
var FontSubZero string

//go:embed fontpack/swampland.txt.gz
var FontSwampLand string

//go:embed fontpack/swan.txt.gz
var FontSwan string

//go:embed fontpack/sweet.txt.gz
var FontSweet string

//go:embed fontpack/this.txt.gz
var FontTHIS string

//go:embed fontpack/tanja.txt.gz
var FontTanja string

//go:embed fontpack/tengwar.txt.gz
var FontTengwar string

//go:embed fontpack/term.txt.gz
var FontTerm string

//go:embed fontpack/test1.txt.gz
var FontTest1 string

//go:embed fontpack/theedge.txt.gz
var FontTheEdge string

//go:embed fontpack/thick.txt.gz
var FontThick string

//go:embed fontpack/thin.txt.gz
var FontThin string

//go:embed fontpack/thorned.txt.gz
var FontThorned string

//go:embed fontpack/threepoint.txt.gz
var FontThreePoint string

//go:embed fontpack/ticks.txt.gz
var FontTicks string

//go:embed fontpack/ticksslant.txt.gz
var FontTicksSlant string

//go:embed fontpack/tiles.txt.gz
var FontTiles string

//go:embed fontpack/tinkertoy.txt.gz
var FontTinkerToy string

//go:embed fontpack/tombstone.txt.gz
var FontTombstone string

//go:embed fontpack/train.txt.gz
var FontTrain string

//go:embed fontpack/trek.txt.gz
var FontTrek string

//go:embed fontpack/tsalagi.txt.gz
var FontTsalagi string

//go:embed fontpack/tubular.txt.gz
var FontTubular string

//go:embed fontpack/twisted.txt.gz
var FontTwisted string

//go:embed fontpack/twopoint.txt.gz
var FontTwoPoint string

//go:embed fontpack/usaflag.txt.gz
var FontUSAFlag string

//go:embed fontpack/univers.txt.gz
var FontUnivers string

//go:embed fontpack/varsity.txt.gz
var FontVarsity string

//go:embed fontpack/wavy.txt.gz
var FontWavy string

//go:embed fontpack/weird.txt.gz
var FontWeird string

//go:embed fontpack/wetletter.txt.gz
var FontWetLetter string

//go:embed fontpack/whimsy.txt.gz
var FontWhimsy string

//go:embed fontpack/wow.txt.gz
var FontWow string

var FontDefault = FontANSIShadow

var FontMap = map[string]string{
	"amc3line":          FontAMC3Line,
	"amc3liv1":          FontAMC3Liv1,
	"amcaaa01":          FontAMCAAA01,
	"amcneko":           FontAMCNeko,
	"amcrazor":          FontAMCRazor,
	"amcrazor2":         FontAMCRazor2,
	"amcslash":          FontAMCSlash,
	"amcslider":         FontAMCSlider,
	"amcthin":           FontAMCThin,
	"amctubes":          FontAMCTubes,
	"amcuntitled":       FontAMCUntitled,
	"ansiregular":       FontANSIRegular,
	"ansishadow":        FontANSIShadow,
	"asciinewroman":     FontASCIINewRoman,
	"acrobatic":         FontAcrobatic,
	"alligator":         FontAlligator,
	"alligator2":        FontAlligator2,
	"alligator3":        FontAlligator3,
	"alpha":             FontAlpha,
	"alphabet":          FontAlphabet,
	"amcrazo2":          FontAmcrazo2,
	"amcslder":          FontAmcslder,
	"amcun1":            FontAmcun1,
	"arrows":            FontArrows,
	"avatar":            FontAvatar,
	"b1ff":              FontB1FF,
	"banner":            FontBanner,
	"banner3":           FontBanner3,
	"banner3d":          FontBanner3D,
	"banner4":           FontBanner4,
	"barbwire":          FontBarbwire,
	"basic":             FontBasic,
	"bear":              FontBear,
	"bell":              FontBell,
	"benjamin":          FontBenjamin,
	"big":               FontBig,
	"bigchief":          FontBigChief,
	"bigmoneyne":        FontBigMoneyne,
	"bigmoneynw":        FontBigMoneynw,
	"bigmoneyse":        FontBigMoneyse,
	"bigmoneysw":        FontBigMoneysw,
	"bigfig":            FontBigfig,
	"binary":            FontBinary,
	"block":             FontBlock,
	"blocks":            FontBlocks,
	"bloody":            FontBloody,
	"bolger":            FontBolger,
	"braced":            FontBraced,
	"bright":            FontBright,
	"broadway":          FontBroadway,
	"broadwaykb":        FontBroadwayKB,
	"bubble":            FontBubble,
	"bulbhead":          FontBulbhead,
	"calgphy2":          FontCalgphy2,
	"caligraphy":        FontCaligraphy,
	"caligraphy2":       FontCaligraphy2,
	"calvins":           FontCalvinS,
	"catwalk":           FontCatwalk,
	"chiseled":          FontChiseled,
	"chunky":            FontChunky,
	"coinstak":          FontCoinstak,
	"cola":              FontCola,
	"colossal":          FontColossal,
	"computer":          FontComputer,
	"contessa":          FontContessa,
	"contrast":          FontContrast,
	"cosmic":            FontCosmic,
	"cosmike":           FontCosmike,
	"crawford":          FontCrawford,
	"crawford2":         FontCrawford2,
	"crazy":             FontCrazy,
	"cricket":           FontCricket,
	"cursive":           FontCursive,
	"cyberlarge":        FontCyberlarge,
	"cybermedium":       FontCybermedium,
	"cybersmall":        FontCybersmall,
	"cygnet":            FontCygnet,
	"danc4":             FontDANC4,
	"dosrebel":          FontDOSRebel,
	"dwhistled":         FontDWhistled,
	"dancingfont":       FontDancingFont,
	"decimal":           FontDecimal,
	"defleppard":        FontDefLeppard,
	"deltacorpspriest1": FontDeltaCorpsPriest1,
	"diamond":           FontDiamond,
	"dietcola":          FontDietCola,
	"digital":           FontDigital,
	"doh":               FontDoh,
	"doom":              FontDoom,
	"dotmatrix":         FontDotMatrix,
	"double":            FontDouble,
	"doubleshorts":      FontDoubleShorts,
	"drpepper":          FontDrPepper,
	"eftichess":         FontEftiChess,
	"eftifont":          FontEftiFont,
	"eftiitalic":        FontEftiItalic,
	"eftipiti":          FontEftiPiti,
	"eftirobot":         FontEftiRobot,
	"eftiwall":          FontEftiWall,
	"eftiwater":         FontEftiWater,
	"eftitalic":         FontEftitalic,
	"electronic":        FontElectronic,
	"elite":             FontElite,
	"epic":              FontEpic,
	"f1row":             FontF1Row,
	"f3d":               FontF3D,
	"f3dascii":          FontF3DASCII,
	"f3ddiagonal":       FontF3DDiagonal,
	"f3x5":              FontF3x5,
	"f4max":             FontF4Max,
	"f5lineoblique":     FontF5LineOblique,
	"fender":            FontFender,
	"filter":            FontFilter,
	"firefontk":         FontFireFontk,
	"firefonts":         FontFireFonts,
	"flipped":           FontFlipped,
	"flowerpower":       FontFlowerPower,
	"fourtops":          FontFourTops,
	"funface":           FontFunFace,
	"funfaces":          FontFunFaces,
	"fuzzy":             FontFuzzy,
	"georgi16":          FontGeorgi16,
	"georgia11":         FontGeorgia11,
	"ghost":             FontGhost,
	"ghoulish":          FontGhoulish,
	"glenyn":            FontGlenyn,
	"goofy":             FontGoofy,
	"gothic":            FontGothic,
	"graceful":          FontGraceful,
	"gradient":          FontGradient,
	"graffiti":          FontGraffiti,
	"greek":             FontGreek,
	"halfiwi":           FontHalfiwi,
	"henry3d":           FontHenry3D,
	"hex":               FontHex,
	"hieroglyphs":       FontHieroglyphs,
	"hollywood":         FontHollywood,
	"horizontalleft":    FontHorizontalLeft,
	"horizontalright":   FontHorizontalRight,
	"icl1900":           FontICL1900,
	"impossible":        FontImpossible,
	"invita":            FontInvita,
	"isometric1":        FontIsometric1,
	"isometric2":        FontIsometric2,
	"isometric3":        FontIsometric3,
	"isometric4":        FontIsometric4,
	"italic":            FontItalic,
	"ivrit":             FontIvrit,
	"jsblockletters":    FontJSBlockLetters,
	"jsbracketletters":  FontJSBracketLetters,
	"jscapitalcurves":   FontJSCapitalCurves,
	"jscursive":         FontJSCursive,
	"jsstickletters":    FontJSStickLetters,
	"jacky":             FontJacky,
	"jazmine":           FontJazmine,
	"jerusalem":         FontJerusalem,
	"katakana":          FontKatakana,
	"kban":              FontKban,
	"keyboard":          FontKeyboard,
	"knob":              FontKnob,
	"konto":             FontKonto,
	"kontoslant":        FontKontoSlant,
	"lcd":               FontLCD,
	"larry3d":           FontLarry3D,
	"larry3d2":          FontLarry3D2,
	"lean":              FontLean,
	"letters":           FontLetters,
	"lildevil":          FontLilDevil,
	"lineblocks":        FontLineBlocks,
	"linux":             FontLinux,
	"lockergnome":       FontLockergnome,
	"madrid":            FontMadrid,
	"marquee":           FontMarquee,
	"maxfour":           FontMaxfour,
	"merlin1":           FontMerlin1,
	"merlin2":           FontMerlin2,
	"mike":              FontMike,
	"mini":              FontMini,
	"mirror":            FontMirror,
	"mnemonic":          FontMnemonic,
	"modular":           FontModular,
	"morse":             FontMorse,
	"morse2":            FontMorse2,
	"moscow":            FontMoscow,
	"mshebrew210":       FontMshebrew210,
	"muzzle":            FontMuzzle,
	"nscript":           FontNScript,
	"ntgreek":           FontNTGreek,
	"nvscript":          FontNVScript,
	"nancyj":            FontNancyj,
	"nancyjfancy":       FontNancyjFancy,
	"nancyjimproved":    FontNancyjImproved,
	"nancyjunderlined":  FontNancyjUnderlined,
	"nipples":           FontNipples,
	"o8":                FontO8,
	"os2":               FontOS2,
	"octal":             FontOctal,
	"ogre":              FontOgre,
	"oldbanner":         FontOldBanner,
	"patorjkhex":        FontPatorjkHeX,
	"patorjkscheese":    FontPatorjksCheese,
	"pawp":              FontPawp,
	"peaks":             FontPeaks,
	"peaksslant":        FontPeaksSlant,
	"pebbles":           FontPebbles,
	"pepper":            FontPepper,
	"poison":            FontPoison,
	"puffy":             FontPuffy,
	"puzzle":            FontPuzzle,
	"pyramid":           FontPyramid,
	"rammstein":         FontRammstein,
	"rectangles":        FontRectangles,
	"redphoenix":        FontRedPhoenix,
	"relief":            FontRelief,
	"relief2":           FontRelief2,
	"rev":               FontRev,
	"reverse":           FontReverse,
	"roman":             FontRoman,
	"rot13":             FontRot13,
	"rotated":           FontRotated,
	"rounded":           FontRounded,
	"rowancap":          FontRowanCap,
	"rozzo":             FontRozzo,
	"runic":             FontRunic,
	"runyc":             FontRunyc,
	"sblood":            FontSBlood,
	"slscript":          FontSLScript,
	"santaclara":        FontSantaClara,
	"script":            FontScript,
	"serifcap":          FontSerifcap,
	"shadow":            FontShadow,
	"shimrod":           FontShimrod,
	"short":             FontShort,
	"slant":             FontSlant,
	"slantrelief":       FontSlantRelief,
	"slide":             FontSlide,
	"small":             FontSmall,
	"smallcaps":         FontSmallCaps,
	"smallisometric1":   FontSmallIsometric1,
	"smallkeyboard":     FontSmallKeyboard,
	"smallpoison":       FontSmallPoison,
	"smallscript":       FontSmallScript,
	"smallshadow":       FontSmallShadow,
	"smallslant":        FontSmallSlant,
	"smalltengwar":      FontSmallTengwar,
	"smisome1":          FontSmisome1,
	"smkeyboard":        FontSmkeyboard,
	"smpoison":          FontSmpoison,
	"smscript":          FontSmscript,
	"smshadow":          FontSmshadow,
	"smslant":           FontSmslant,
	"smtengwar":         FontSmtengwar,
	"soft":              FontSoft,
	"speed":             FontSpeed,
	"spliff":            FontSpliff,
	"srelief":           FontSrelief,
	"stacey":            FontStacey,
	"stampate":          FontStampate,
	"stampatello":       FontStampatello,
	"standard":          FontStandard,
	"starstrips":        FontStarStrips,
	"starwars":          FontStarWars,
	"stellar":           FontStellar,
	"stforek":           FontStforek,
	"stickletters":      FontStickLetters,
	"stop":              FontStop,
	"straight":          FontStraight,
	"strongerthanall":   FontStrongerThanAll,
	"subzero":           FontSubZero,
	"swampland":         FontSwampLand,
	"swan":              FontSwan,
	"sweet":             FontSweet,
	"this":              FontTHIS,
	"tanja":             FontTanja,
	"tengwar":           FontTengwar,
	"term":              FontTerm,
	"test1":             FontTest1,
	"theedge":           FontTheEdge,
	"thick":             FontThick,
	"thin":              FontThin,
	"thorned":           FontThorned,
	"threepoint":        FontThreePoint,
	"ticks":             FontTicks,
	"ticksslant":        FontTicksSlant,
	"tiles":             FontTiles,
	"tinkertoy":         FontTinkerToy,
	"tombstone":         FontTombstone,
	"train":             FontTrain,
	"trek":              FontTrek,
	"tsalagi":           FontTsalagi,
	"tubular":           FontTubular,
	"twisted":           FontTwisted,
	"twopoint":          FontTwoPoint,
	"usaflag":           FontUSAFlag,
	"univers":           FontUnivers,
	"varsity":           FontVarsity,
	"wavy":              FontWavy,
	"weird":             FontWeird,
	"wetletter":         FontWetLetter,
	"whimsy":            FontWhimsy,
	"wow":               FontWow,

	"default": FontANSIShadow,
}

func GetFont(f string) string {
	if val, ok := FontMap[strings.ToLower(f)]; ok {
		return val
	}
	fmt.Println("Font not found, using default font")
	return GetFont("default")
}
