// Package asciiban Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2023-08-16 12:15:17.309606 +1000 AEST m=+1.222905084
// using data from https://github.com/xero/figlet-fonts
package asciiban

import (
	"github.com/socialviolation/asciiban/fontpack"
	"strings"
)

const FontAMC3Line = fontpack.AMC3Line
const FontAMC3Liv1 = fontpack.AMC3Liv1
const FontAMCAAA01 = fontpack.AMCAAA01
const FontAMCNeko = fontpack.AMCNeko
const FontAMCRazor = fontpack.AMCRazor
const FontAMCRazor2 = fontpack.AMCRazor2
const FontAMCSlash = fontpack.AMCSlash
const FontAMCSlider = fontpack.AMCSlider
const FontAMCThin = fontpack.AMCThin
const FontAMCTubes = fontpack.AMCTubes
const FontAMCUntitled = fontpack.AMCUntitled
const FontANSIRegular = fontpack.ANSIRegular
const FontANSIShadow = fontpack.ANSIShadow
const FontAcrobatic = fontpack.Acrobatic
const FontAlligator = fontpack.Alligator
const FontAlligator2 = fontpack.Alligator2
const FontAlligator3 = fontpack.Alligator3
const FontAlpha = fontpack.Alpha
const FontAlphabet = fontpack.Alphabet
const FontAmcrazo2 = fontpack.Amcrazo2
const FontAmcslder = fontpack.Amcslder
const FontAmcun1 = fontpack.Amcun1
const FontArrows = fontpack.Arrows
const FontAvatar = fontpack.Avatar
const FontBanner = fontpack.Banner
const FontBanner3 = fontpack.Banner3
const FontBanner3D = fontpack.Banner3D
const FontBanner4 = fontpack.Banner4
const FontBarbwire = fontpack.Barbwire
const FontBasic = fontpack.Basic
const FontBell = fontpack.Bell
const FontBenjamin = fontpack.Benjamin
const FontBig = fontpack.Big
const FontBigChief = fontpack.BigChief
const FontBigMoneyne = fontpack.BigMoneyne
const FontBigMoneynw = fontpack.BigMoneynw
const FontBigMoneyse = fontpack.BigMoneyse
const FontBigMoneysw = fontpack.BigMoneysw
const FontBigfig = fontpack.Bigfig
const FontBinary = fontpack.Binary
const FontBlock = fontpack.Block
const FontBloody = fontpack.Bloody
const FontBolger = fontpack.Bolger
const FontBraced = fontpack.Braced
const FontBright = fontpack.Bright
const FontBroadway = fontpack.Broadway
const FontBulbhead = fontpack.Bulbhead
const FontCalgphy2 = fontpack.Calgphy2
const FontCaligraphy = fontpack.Caligraphy
const FontCaligraphy2 = fontpack.Caligraphy2
const FontCalvinS = fontpack.CalvinS
const FontCatwalk = fontpack.Catwalk
const FontChunky = fontpack.Chunky
const FontCoinstak = fontpack.Coinstak
const FontColossal = fontpack.Colossal
const FontComputer = fontpack.Computer
const FontContessa = fontpack.Contessa
const FontContrast = fontpack.Contrast
const FontCosmic = fontpack.Cosmic
const FontCosmike = fontpack.Cosmike
const FontCrawford = fontpack.Crawford
const FontCrawford2 = fontpack.Crawford2
const FontCricket = fontpack.Cricket
const FontCursive = fontpack.Cursive
const FontCyberlarge = fontpack.Cyberlarge
const FontCybermedium = fontpack.Cybermedium
const FontCybersmall = fontpack.Cybersmall
const FontCygnet = fontpack.Cygnet
const FontDANC4 = fontpack.DANC4
const FontDOSRebel = fontpack.DOSRebel
const FontDecimal = fontpack.Decimal
const FontDefLeppard = fontpack.DefLeppard
const FontDeltaCorpsPriest1 = fontpack.DeltaCorpsPriest1
const FontDiamond = fontpack.Diamond
const FontDoh = fontpack.Doh
const FontDoom = fontpack.Doom
const FontDotMatrix = fontpack.DotMatrix
const FontDouble = fontpack.Double
const FontDoubleShorts = fontpack.DoubleShorts
const FontDrPepper = fontpack.DrPepper
const FontEftiChess = fontpack.EftiChess
const FontEftiFont = fontpack.EftiFont
const FontEftiItalic = fontpack.EftiItalic
const FontEftiPiti = fontpack.EftiPiti
const FontEftiRobot = fontpack.EftiRobot
const FontEftiWall = fontpack.EftiWall
const FontEftiWater = fontpack.EftiWater
const FontEftitalic = fontpack.Eftitalic
const FontElectronic = fontpack.Electronic
const FontElite = fontpack.Elite
const FontEpic = fontpack.Epic
const FontF1Row = fontpack.F1Row
const FontF3D = fontpack.F3D
const FontF3DASCII = fontpack.F3DASCII
const FontF3x5 = fontpack.F3x5
const FontF4Max = fontpack.F4Max
const FontF5LineOblique = fontpack.F5LineOblique
const FontFender = fontpack.Fender
const FontFireFontk = fontpack.FireFontk
const FontFireFonts = fontpack.FireFonts
const FontFourTops = fontpack.FourTops
const FontFuzzy = fontpack.Fuzzy
const FontGeorgi16 = fontpack.Georgi16
const FontGeorgia11 = fontpack.Georgia11
const FontGoofy = fontpack.Goofy
const FontGothic = fontpack.Gothic
const FontGraceful = fontpack.Graceful
const FontGradient = fontpack.Gradient
const FontGraffiti = fontpack.Graffiti
const FontGreek = fontpack.Greek
const FontHalfiwi = fontpack.Halfiwi
const FontHenry3D = fontpack.Henry3D
const FontHex = fontpack.Hex
const FontHollywood = fontpack.Hollywood
const FontInvita = fontpack.Invita
const FontIsometric1 = fontpack.Isometric1
const FontIsometric2 = fontpack.Isometric2
const FontIsometric3 = fontpack.Isometric3
const FontIsometric4 = fontpack.Isometric4
const FontItalic = fontpack.Italic
const FontIvrit = fontpack.Ivrit
const FontJSBlockLetters = fontpack.JSBlockLetters
const FontJSBracketLetters = fontpack.JSBracketLetters
const FontJSCursive = fontpack.JSCursive
const FontJSStickLetters = fontpack.JSStickLetters
const FontJacky = fontpack.Jacky
const FontJazmine = fontpack.Jazmine
const FontJerusalem = fontpack.Jerusalem
const FontKatakana = fontpack.Katakana
const FontKban = fontpack.Kban
const FontKeyboard = fontpack.Keyboard
const FontLCD = fontpack.LCD
const FontLarry3D = fontpack.Larry3D
const FontLarry3D2 = fontpack.Larry3D2
const FontLean = fontpack.Lean
const FontLetters = fontpack.Letters
const FontLinux = fontpack.Linux
const FontLockergnome = fontpack.Lockergnome
const FontMadrid = fontpack.Madrid
const FontMarquee = fontpack.Marquee
const FontMaxfour = fontpack.Maxfour
const FontMike = fontpack.Mike
const FontMini = fontpack.Mini
const FontMirror = fontpack.Mirror
const FontMnemonic = fontpack.Mnemonic
const FontMorse = fontpack.Morse
const FontMorse2 = fontpack.Morse2
const FontMoscow = fontpack.Moscow
const FontMshebrew210 = fontpack.Mshebrew210
const FontNScript = fontpack.NScript
const FontNTGreek = fontpack.NTGreek
const FontNVScript = fontpack.NVScript
const FontNancyj = fontpack.Nancyj
const FontNancyjFancy = fontpack.NancyjFancy
const FontNancyjImproved = fontpack.NancyjImproved
const FontNancyjUnderlined = fontpack.NancyjUnderlined
const FontNipples = fontpack.Nipples
const FontO8 = fontpack.O8
const FontOS2 = fontpack.OS2
const FontOctal = fontpack.Octal
const FontOgre = fontpack.Ogre
const FontOldBanner = fontpack.OldBanner
const FontPatorjkHeX = fontpack.PatorjkHeX
const FontPatorjksCheese = fontpack.PatorjksCheese
const FontPawp = fontpack.Pawp
const FontPeaks = fontpack.Peaks
const FontPeaksSlant = fontpack.PeaksSlant
const FontPebbles = fontpack.Pebbles
const FontPepper = fontpack.Pepper
const FontPoison = fontpack.Poison
const FontPuffy = fontpack.Puffy
const FontPuzzle = fontpack.Puzzle
const FontRectangles = fontpack.Rectangles
const FontRedPhoenix = fontpack.RedPhoenix
const FontRelief = fontpack.Relief
const FontRelief2 = fontpack.Relief2
const FontRev = fontpack.Rev
const FontReverse = fontpack.Reverse
const FontRoman = fontpack.Roman
const FontRounded = fontpack.Rounded
const FontRowanCap = fontpack.RowanCap
const FontRozzo = fontpack.Rozzo
const FontRunic = fontpack.Runic
const FontRunyc = fontpack.Runyc
const FontSBlood = fontpack.SBlood
const FontSLScript = fontpack.SLScript
const FontSantaClara = fontpack.SantaClara
const FontScript = fontpack.Script
const FontSerifcap = fontpack.Serifcap
const FontShadow = fontpack.Shadow
const FontShimrod = fontpack.Shimrod
const FontShort = fontpack.Short
const FontSlant = fontpack.Slant
const FontSlantRelief = fontpack.SlantRelief
const FontSlide = fontpack.Slide
const FontSmall = fontpack.Small
const FontSmallIsometric1 = fontpack.SmallIsometric1
const FontSmallKeyboard = fontpack.SmallKeyboard
const FontSmallPoison = fontpack.SmallPoison
const FontSmallScript = fontpack.SmallScript
const FontSmallShadow = fontpack.SmallShadow
const FontSmallSlant = fontpack.SmallSlant
const FontSmallTengwar = fontpack.SmallTengwar
const FontSmisome1 = fontpack.Smisome1
const FontSmkeyboard = fontpack.Smkeyboard
const FontSmpoison = fontpack.Smpoison
const FontSmscript = fontpack.Smscript
const FontSmshadow = fontpack.Smshadow
const FontSmslant = fontpack.Smslant
const FontSmtengwar = fontpack.Smtengwar
const FontSpeed = fontpack.Speed
const FontSrelief = fontpack.Srelief
const FontStacey = fontpack.Stacey
const FontStampate = fontpack.Stampate
const FontStampatello = fontpack.Stampatello
const FontStandard = fontpack.Standard
const FontStarWars = fontpack.StarWars
const FontStellar = fontpack.Stellar
const FontStforek = fontpack.Stforek
const FontStickLetters = fontpack.StickLetters
const FontStop = fontpack.Stop
const FontStraight = fontpack.Straight
const FontStrongerThanAll = fontpack.StrongerThanAll
const FontSubZero = fontpack.SubZero
const FontSwan = fontpack.Swan
const FontTHIS = fontpack.THIS
const FontTanja = fontpack.Tanja
const FontTengwar = fontpack.Tengwar
const FontTest1 = fontpack.Test1
const FontTheEdge = fontpack.TheEdge
const FontThick = fontpack.Thick
const FontThin = fontpack.Thin
const FontThreePoint = fontpack.ThreePoint
const FontTicks = fontpack.Ticks
const FontTicksSlant = fontpack.TicksSlant
const FontTiles = fontpack.Tiles
const FontTinkerToy = fontpack.TinkerToy
const FontTombstone = fontpack.Tombstone
const FontTrek = fontpack.Trek
const FontTubular = fontpack.Tubular
const FontTwoPoint = fontpack.TwoPoint
const FontUSAFlag = fontpack.USAFlag
const FontUnivers = fontpack.Univers
const FontWavy = fontpack.Wavy
const FontWeird = fontpack.Weird
const FontWhimsy = fontpack.Whimsy

func GetFont(f string) string {
	if val, ok := FontMap[strings.ToLower(f)]; ok {
		return val
	}
	return GetFont("default")
}

var FontMap = map[string]string{
	"amc3line":          FontAMC3Line,
	"amc3liv1":          FontAMC3Liv1,
	"amcaaa01":          FontAMCAAA01,
	"amcneko":           FontAMCNeko,
	"amcrazor":          FontAMCRazor,
	"amcrazor2":         FontAMCRazor2,
	"amcslash":          FontAMCSlash,
	"amcslider":         FontAMCSlider,
	"amcthin":           FontAMCThin,
	"amctubes":          FontAMCTubes,
	"amcuntitled":       FontAMCUntitled,
	"ansiregular":       FontANSIRegular,
	"ansishadow":        FontANSIShadow,
	"acrobatic":         FontAcrobatic,
	"alligator":         FontAlligator,
	"alligator2":        FontAlligator2,
	"alligator3":        FontAlligator3,
	"alpha":             FontAlpha,
	"alphabet":          FontAlphabet,
	"amcrazo2":          FontAmcrazo2,
	"amcslder":          FontAmcslder,
	"amcun1":            FontAmcun1,
	"arrows":            FontArrows,
	"avatar":            FontAvatar,
	"banner":            FontBanner,
	"banner3":           FontBanner3,
	"banner3d":          FontBanner3D,
	"banner4":           FontBanner4,
	"barbwire":          FontBarbwire,
	"basic":             FontBasic,
	"bell":              FontBell,
	"benjamin":          FontBenjamin,
	"big":               FontBig,
	"bigchief":          FontBigChief,
	"bigmoneyne":        FontBigMoneyne,
	"bigmoneynw":        FontBigMoneynw,
	"bigmoneyse":        FontBigMoneyse,
	"bigmoneysw":        FontBigMoneysw,
	"bigfig":            FontBigfig,
	"binary":            FontBinary,
	"block":             FontBlock,
	"bloody":            FontBloody,
	"bolger":            FontBolger,
	"braced":            FontBraced,
	"bright":            FontBright,
	"broadway":          FontBroadway,
	"bulbhead":          FontBulbhead,
	"calgphy2":          FontCalgphy2,
	"caligraphy":        FontCaligraphy,
	"caligraphy2":       FontCaligraphy2,
	"calvins":           FontCalvinS,
	"catwalk":           FontCatwalk,
	"chunky":            FontChunky,
	"coinstak":          FontCoinstak,
	"colossal":          FontColossal,
	"computer":          FontComputer,
	"contessa":          FontContessa,
	"contrast":          FontContrast,
	"cosmic":            FontCosmic,
	"cosmike":           FontCosmike,
	"crawford":          FontCrawford,
	"crawford2":         FontCrawford2,
	"cricket":           FontCricket,
	"cursive":           FontCursive,
	"cyberlarge":        FontCyberlarge,
	"cybermedium":       FontCybermedium,
	"cybersmall":        FontCybersmall,
	"cygnet":            FontCygnet,
	"danc4":             FontDANC4,
	"dosrebel":          FontDOSRebel,
	"decimal":           FontDecimal,
	"defleppard":        FontDefLeppard,
	"deltacorpspriest1": FontDeltaCorpsPriest1,
	"diamond":           FontDiamond,
	"doh":               FontDoh,
	"doom":              FontDoom,
	"dotmatrix":         FontDotMatrix,
	"double":            FontDouble,
	"doubleshorts":      FontDoubleShorts,
	"drpepper":          FontDrPepper,
	"eftichess":         FontEftiChess,
	"eftifont":          FontEftiFont,
	"eftiitalic":        FontEftiItalic,
	"eftipiti":          FontEftiPiti,
	"eftirobot":         FontEftiRobot,
	"eftiwall":          FontEftiWall,
	"eftiwater":         FontEftiWater,
	"eftitalic":         FontEftitalic,
	"electronic":        FontElectronic,
	"elite":             FontElite,
	"epic":              FontEpic,
	"f1row":             FontF1Row,
	"f3d":               FontF3D,
	"f3dascii":          FontF3DASCII,
	"f3x5":              FontF3x5,
	"f4max":             FontF4Max,
	"f5lineoblique":     FontF5LineOblique,
	"fender":            FontFender,
	"firefontk":         FontFireFontk,
	"firefonts":         FontFireFonts,
	"fourtops":          FontFourTops,
	"fuzzy":             FontFuzzy,
	"georgi16":          FontGeorgi16,
	"georgia11":         FontGeorgia11,
	"goofy":             FontGoofy,
	"gothic":            FontGothic,
	"graceful":          FontGraceful,
	"gradient":          FontGradient,
	"graffiti":          FontGraffiti,
	"greek":             FontGreek,
	"halfiwi":           FontHalfiwi,
	"henry3d":           FontHenry3D,
	"hex":               FontHex,
	"hollywood":         FontHollywood,
	"invita":            FontInvita,
	"isometric1":        FontIsometric1,
	"isometric2":        FontIsometric2,
	"isometric3":        FontIsometric3,
	"isometric4":        FontIsometric4,
	"italic":            FontItalic,
	"ivrit":             FontIvrit,
	"jsblockletters":    FontJSBlockLetters,
	"jsbracketletters":  FontJSBracketLetters,
	"jscursive":         FontJSCursive,
	"jsstickletters":    FontJSStickLetters,
	"jacky":             FontJacky,
	"jazmine":           FontJazmine,
	"jerusalem":         FontJerusalem,
	"katakana":          FontKatakana,
	"kban":              FontKban,
	"keyboard":          FontKeyboard,
	"lcd":               FontLCD,
	"larry3d":           FontLarry3D,
	"larry3d2":          FontLarry3D2,
	"lean":              FontLean,
	"letters":           FontLetters,
	"linux":             FontLinux,
	"lockergnome":       FontLockergnome,
	"madrid":            FontMadrid,
	"marquee":           FontMarquee,
	"maxfour":           FontMaxfour,
	"mike":              FontMike,
	"mini":              FontMini,
	"mirror":            FontMirror,
	"mnemonic":          FontMnemonic,
	"morse":             FontMorse,
	"morse2":            FontMorse2,
	"moscow":            FontMoscow,
	"mshebrew210":       FontMshebrew210,
	"nscript":           FontNScript,
	"ntgreek":           FontNTGreek,
	"nvscript":          FontNVScript,
	"nancyj":            FontNancyj,
	"nancyjfancy":       FontNancyjFancy,
	"nancyjimproved":    FontNancyjImproved,
	"nancyjunderlined":  FontNancyjUnderlined,
	"nipples":           FontNipples,
	"o8":                FontO8,
	"os2":               FontOS2,
	"octal":             FontOctal,
	"ogre":              FontOgre,
	"oldbanner":         FontOldBanner,
	"patorjkhex":        FontPatorjkHeX,
	"patorjkscheese":    FontPatorjksCheese,
	"pawp":              FontPawp,
	"peaks":             FontPeaks,
	"peaksslant":        FontPeaksSlant,
	"pebbles":           FontPebbles,
	"pepper":            FontPepper,
	"poison":            FontPoison,
	"puffy":             FontPuffy,
	"puzzle":            FontPuzzle,
	"rectangles":        FontRectangles,
	"redphoenix":        FontRedPhoenix,
	"relief":            FontRelief,
	"relief2":           FontRelief2,
	"rev":               FontRev,
	"reverse":           FontReverse,
	"roman":             FontRoman,
	"rounded":           FontRounded,
	"rowancap":          FontRowanCap,
	"rozzo":             FontRozzo,
	"runic":             FontRunic,
	"runyc":             FontRunyc,
	"sblood":            FontSBlood,
	"slscript":          FontSLScript,
	"santaclara":        FontSantaClara,
	"script":            FontScript,
	"serifcap":          FontSerifcap,
	"shadow":            FontShadow,
	"shimrod":           FontShimrod,
	"short":             FontShort,
	"slant":             FontSlant,
	"slantrelief":       FontSlantRelief,
	"slide":             FontSlide,
	"small":             FontSmall,
	"smallisometric1":   FontSmallIsometric1,
	"smallkeyboard":     FontSmallKeyboard,
	"smallpoison":       FontSmallPoison,
	"smallscript":       FontSmallScript,
	"smallshadow":       FontSmallShadow,
	"smallslant":        FontSmallSlant,
	"smalltengwar":      FontSmallTengwar,
	"smisome1":          FontSmisome1,
	"smkeyboard":        FontSmkeyboard,
	"smpoison":          FontSmpoison,
	"smscript":          FontSmscript,
	"smshadow":          FontSmshadow,
	"smslant":           FontSmslant,
	"smtengwar":         FontSmtengwar,
	"speed":             FontSpeed,
	"srelief":           FontSrelief,
	"stacey":            FontStacey,
	"stampate":          FontStampate,
	"stampatello":       FontStampatello,
	"standard":          FontStandard,
	"starwars":          FontStarWars,
	"stellar":           FontStellar,
	"stforek":           FontStforek,
	"stickletters":      FontStickLetters,
	"stop":              FontStop,
	"straight":          FontStraight,
	"strongerthanall":   FontStrongerThanAll,
	"subzero":           FontSubZero,
	"swan":              FontSwan,
	"this":              FontTHIS,
	"tanja":             FontTanja,
	"tengwar":           FontTengwar,
	"test1":             FontTest1,
	"theedge":           FontTheEdge,
	"thick":             FontThick,
	"thin":              FontThin,
	"threepoint":        FontThreePoint,
	"ticks":             FontTicks,
	"ticksslant":        FontTicksSlant,
	"tiles":             FontTiles,
	"tinkertoy":         FontTinkerToy,
	"tombstone":         FontTombstone,
	"trek":              FontTrek,
	"tubular":           FontTubular,
	"twopoint":          FontTwoPoint,
	"usaflag":           FontUSAFlag,
	"univers":           FontUnivers,
	"wavy":              FontWavy,
	"weird":             FontWeird,
	"whimsy":            FontWhimsy,

	"default": FontANSIShadow,
}
