// Package fontpack Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2023-04-07 10:52:05.993096 +1000 AEST m=+5.413946077
// using data from https://github.com/xero/figlet-fonts
package fontpack

const Mshebrew210 = `flf2a$ 4 3 10 -1 13 1
mshebrew210.flf by Michael 'msh210' Hamm 2-5 Nov 2000 for FIGWin.
Copyright (c) 2000 Michael Hamm. Note: uses Gedaliah Friedenberg's
Jerusalem font's keyboard map. www.crosswinds.net/~msh210/ has
msh210 contact info. Okay to modify this font iff modifier's name
is on a comment line. msh210's first font: have heart, suggestions

Keyboard map (see note above):
alef  = t | vav   = u | chaf   = f | nun    = b | fe     = p | kuf  = e
ves   = c | zayin = z | ` + "`" + `final = l | ` + "`" + `final = i | ` + "`" + `final = ; | resh = r
gimel = d | ches  = j | lamed  = k | samach = x | tzadi  = m | shin = a
daled = s | tes   = y | mem    = n | ayin   = g | ` + "`" + `final = . | saf  = ,
he    = v | yud   = h | ` + "`" + `final = o |                         period = /

$@
$@
$@
$@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
     @
 |""|@
_|  |@
     @@
@
@
@
@@
    @
\  |@
 \/ @
 $\ @@
 @
 @
o@
 @@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
   @
["|@
  |@
  |@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
    @
|/ |@
|_/ @
    @@
  @
$|@
_|@
  @@
    @
""| @
__|_@
    @@
  @
\ @
/\@
  @@
   @
""|@
| '@
|$ @@
   @
""|@
__|@
   @@
    @
\  |@
 \/ @
-'$ @@
 @
|@
$@
 @@
 @
|@
|@
|@@
    @
|""|@
|  |@
    @@
|$  @
 ""|@
  / @
    @@
   @
""|@
  |@
  |@@
  @
\/@
_\@
  @@
    @
Y"\ @
| _|@
    @@
    @
|""|@
|__|@
    @@
   @
["|@
__|@
   @@
@
@
@
@@
   @
""|@
  |@
  $@@
    @
""|'@
  | @
  $ @@
  @
\>@
L\@
  @@
 @
|@
|@
$@@
   @
""|@
| |@
  $@@
@
@
@
@@
    @
|""|@
 \/ @
    @@
    @
| /|@
|__|@
    @@
   @
` + "`" + `(` + "`" + `@
  )@
   @@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
@
@
@
@@
`
