// Package ascii Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2023-08-21 23:28:50.259586 +1000 AEST m=+1.108248043
// using data from https://github.com/xero/figlet-fonts

//go:build !exclude

package ascii

import (
	_ "embed"
	"fmt"
	"strings"
)

//go:embed ascii/fontpack/amc3line.flf.gz
var fontAMC3Line string

//go:embed ascii/fontpack/amc3liv1.flf.gz
var fontAMC3Liv1 string

//go:embed ascii/fontpack/amcaaa01.flf.gz
var fontAMCAAA01 string

//go:embed ascii/fontpack/amcneko.flf.gz
var fontAMCNeko string

//go:embed ascii/fontpack/amcrazor.flf.gz
var fontAMCRazor string

//go:embed ascii/fontpack/amcrazor2.flf.gz
var fontAMCRazor2 string

//go:embed ascii/fontpack/amcslash.flf.gz
var fontAMCSlash string

//go:embed ascii/fontpack/amcslider.flf.gz
var fontAMCSlider string

//go:embed ascii/fontpack/amcthin.flf.gz
var fontAMCThin string

//go:embed ascii/fontpack/amctubes.flf.gz
var fontAMCTubes string

//go:embed ascii/fontpack/amcuntitled.flf.gz
var fontAMCUntitled string

//go:embed ascii/fontpack/ansiregular.flf.gz
var fontANSIRegular string

//go:embed ascii/fontpack/ansishadow.flf.gz
var fontANSIShadow string

//go:embed ascii/fontpack/asciinewroman.flf.gz
var fontASCIINewRoman string

//go:embed ascii/fontpack/acrobatic.flf.gz
var fontAcrobatic string

//go:embed ascii/fontpack/alligator.flf.gz
var fontAlligator string

//go:embed ascii/fontpack/alligator2.flf.gz
var fontAlligator2 string

//go:embed ascii/fontpack/alligator3.flf.gz
var fontAlligator3 string

//go:embed ascii/fontpack/alpha.flf.gz
var fontAlpha string

//go:embed ascii/fontpack/alphabet.flf.gz
var fontAlphabet string

//go:embed ascii/fontpack/amcrazo2.flf.gz
var fontAmcrazo2 string

//go:embed ascii/fontpack/amcslder.flf.gz
var fontAmcslder string

//go:embed ascii/fontpack/amcun1.flf.gz
var fontAmcun1 string

//go:embed ascii/fontpack/arrows.flf.gz
var fontArrows string

//go:embed ascii/fontpack/avatar.flf.gz
var fontAvatar string

//go:embed ascii/fontpack/b1ff.flf.gz
var fontB1FF string

//go:embed ascii/fontpack/banner.flf.gz
var fontBanner string

//go:embed ascii/fontpack/banner3.flf.gz
var fontBanner3 string

//go:embed ascii/fontpack/banner3d.flf.gz
var fontBanner3D string

//go:embed ascii/fontpack/banner4.flf.gz
var fontBanner4 string

//go:embed ascii/fontpack/barbwire.flf.gz
var fontBarbwire string

//go:embed ascii/fontpack/basic.flf.gz
var fontBasic string

//go:embed ascii/fontpack/bear.flf.gz
var fontBear string

//go:embed ascii/fontpack/bell.flf.gz
var fontBell string

//go:embed ascii/fontpack/benjamin.flf.gz
var fontBenjamin string

//go:embed ascii/fontpack/big.flf.gz
var fontBig string

//go:embed ascii/fontpack/bigchief.flf.gz
var fontBigChief string

//go:embed ascii/fontpack/bigmoneyne.flf.gz
var fontBigMoneyne string

//go:embed ascii/fontpack/bigmoneynw.flf.gz
var fontBigMoneynw string

//go:embed ascii/fontpack/bigmoneyse.flf.gz
var fontBigMoneyse string

//go:embed ascii/fontpack/bigmoneysw.flf.gz
var fontBigMoneysw string

//go:embed ascii/fontpack/bigfig.flf.gz
var fontBigfig string

//go:embed ascii/fontpack/binary.flf.gz
var fontBinary string

//go:embed ascii/fontpack/block.flf.gz
var fontBlock string

//go:embed ascii/fontpack/blocks.flf.gz
var fontBlocks string

//go:embed ascii/fontpack/bloody.flf.gz
var fontBloody string

//go:embed ascii/fontpack/bolger.flf.gz
var fontBolger string

//go:embed ascii/fontpack/braced.flf.gz
var fontBraced string

//go:embed ascii/fontpack/bright.flf.gz
var fontBright string

//go:embed ascii/fontpack/broadway.flf.gz
var fontBroadway string

//go:embed ascii/fontpack/broadwaykb.flf.gz
var fontBroadwayKB string

//go:embed ascii/fontpack/bubble.flf.gz
var fontBubble string

//go:embed ascii/fontpack/bulbhead.flf.gz
var fontBulbhead string

//go:embed ascii/fontpack/calgphy2.flf.gz
var fontCalgphy2 string

//go:embed ascii/fontpack/caligraphy.flf.gz
var fontCaligraphy string

//go:embed ascii/fontpack/caligraphy2.flf.gz
var fontCaligraphy2 string

//go:embed ascii/fontpack/calvins.flf.gz
var fontCalvinS string

//go:embed ascii/fontpack/catwalk.flf.gz
var fontCatwalk string

//go:embed ascii/fontpack/chiseled.flf.gz
var fontChiseled string

//go:embed ascii/fontpack/chunky.flf.gz
var fontChunky string

//go:embed ascii/fontpack/coinstak.flf.gz
var fontCoinstak string

//go:embed ascii/fontpack/cola.flf.gz
var fontCola string

//go:embed ascii/fontpack/colossal.flf.gz
var fontColossal string

//go:embed ascii/fontpack/computer.flf.gz
var fontComputer string

//go:embed ascii/fontpack/contessa.flf.gz
var fontContessa string

//go:embed ascii/fontpack/contrast.flf.gz
var fontContrast string

//go:embed ascii/fontpack/cosmic.flf.gz
var fontCosmic string

//go:embed ascii/fontpack/cosmike.flf.gz
var fontCosmike string

//go:embed ascii/fontpack/crawford.flf.gz
var fontCrawford string

//go:embed ascii/fontpack/crawford2.flf.gz
var fontCrawford2 string

//go:embed ascii/fontpack/crazy.flf.gz
var fontCrazy string

//go:embed ascii/fontpack/cricket.flf.gz
var fontCricket string

//go:embed ascii/fontpack/cursive.flf.gz
var fontCursive string

//go:embed ascii/fontpack/cyberlarge.flf.gz
var fontCyberlarge string

//go:embed ascii/fontpack/cybermedium.flf.gz
var fontCybermedium string

//go:embed ascii/fontpack/cybersmall.flf.gz
var fontCybersmall string

//go:embed ascii/fontpack/cygnet.flf.gz
var fontCygnet string

//go:embed ascii/fontpack/danc4.flf.gz
var fontDANC4 string

//go:embed ascii/fontpack/dosrebel.flf.gz
var fontDOSRebel string

//go:embed ascii/fontpack/dwhistled.flf.gz
var fontDWhistled string

//go:embed ascii/fontpack/dancingfont.flf.gz
var fontDancingFont string

//go:embed ascii/fontpack/decimal.flf.gz
var fontDecimal string

//go:embed ascii/fontpack/defleppard.flf.gz
var fontDefLeppard string

//go:embed ascii/fontpack/deltacorpspriest1.flf.gz
var fontDeltaCorpsPriest1 string

//go:embed ascii/fontpack/diamond.flf.gz
var fontDiamond string

//go:embed ascii/fontpack/dietcola.flf.gz
var fontDietCola string

//go:embed ascii/fontpack/digital.flf.gz
var fontDigital string

//go:embed ascii/fontpack/doh.flf.gz
var fontDoh string

//go:embed ascii/fontpack/doom.flf.gz
var fontDoom string

//go:embed ascii/fontpack/dotmatrix.flf.gz
var fontDotMatrix string

//go:embed ascii/fontpack/double.flf.gz
var fontDouble string

//go:embed ascii/fontpack/doubleshorts.flf.gz
var fontDoubleShorts string

//go:embed ascii/fontpack/drpepper.flf.gz
var fontDrPepper string

//go:embed ascii/fontpack/eftichess.flf.gz
var fontEftiChess string

//go:embed ascii/fontpack/eftifont.flf.gz
var fontEftiFont string

//go:embed ascii/fontpack/eftiitalic.flf.gz
var fontEftiItalic string

//go:embed ascii/fontpack/eftipiti.flf.gz
var fontEftiPiti string

//go:embed ascii/fontpack/eftirobot.flf.gz
var fontEftiRobot string

//go:embed ascii/fontpack/eftiwall.flf.gz
var fontEftiWall string

//go:embed ascii/fontpack/eftiwater.flf.gz
var fontEftiWater string

//go:embed ascii/fontpack/eftitalic.flf.gz
var fontEftitalic string

//go:embed ascii/fontpack/electronic.flf.gz
var fontElectronic string

//go:embed ascii/fontpack/elite.flf.gz
var fontElite string

//go:embed ascii/fontpack/epic.flf.gz
var fontEpic string

//go:embed ascii/fontpack/f1row.flf.gz
var fontF1Row string

//go:embed ascii/fontpack/f3d.flf.gz
var fontF3D string

//go:embed ascii/fontpack/f3dascii.flf.gz
var fontF3DASCII string

//go:embed ascii/fontpack/f3ddiagonal.flf.gz
var fontF3DDiagonal string

//go:embed ascii/fontpack/f3x5.flf.gz
var fontF3x5 string

//go:embed ascii/fontpack/f4max.flf.gz
var fontF4Max string

//go:embed ascii/fontpack/f5lineoblique.flf.gz
var fontF5LineOblique string

//go:embed ascii/fontpack/fender.flf.gz
var fontFender string

//go:embed ascii/fontpack/filter.flf.gz
var fontFilter string

//go:embed ascii/fontpack/firefontk.flf.gz
var fontFireFontk string

//go:embed ascii/fontpack/firefonts.flf.gz
var fontFireFonts string

//go:embed ascii/fontpack/flipped.flf.gz
var fontFlipped string

//go:embed ascii/fontpack/flowerpower.flf.gz
var fontFlowerPower string

//go:embed ascii/fontpack/fourtops.flf.gz
var fontFourTops string

//go:embed ascii/fontpack/funface.flf.gz
var fontFunFace string

//go:embed ascii/fontpack/funfaces.flf.gz
var fontFunFaces string

//go:embed ascii/fontpack/fuzzy.flf.gz
var fontFuzzy string

//go:embed ascii/fontpack/georgi16.flf.gz
var fontGeorgi16 string

//go:embed ascii/fontpack/georgia11.flf.gz
var fontGeorgia11 string

//go:embed ascii/fontpack/ghost.flf.gz
var fontGhost string

//go:embed ascii/fontpack/ghoulish.flf.gz
var fontGhoulish string

//go:embed ascii/fontpack/glenyn.flf.gz
var fontGlenyn string

//go:embed ascii/fontpack/goofy.flf.gz
var fontGoofy string

//go:embed ascii/fontpack/gothic.flf.gz
var fontGothic string

//go:embed ascii/fontpack/graceful.flf.gz
var fontGraceful string

//go:embed ascii/fontpack/gradient.flf.gz
var fontGradient string

//go:embed ascii/fontpack/graffiti.flf.gz
var fontGraffiti string

//go:embed ascii/fontpack/greek.flf.gz
var fontGreek string

//go:embed ascii/fontpack/halfiwi.flf.gz
var fontHalfiwi string

//go:embed ascii/fontpack/henry3d.flf.gz
var fontHenry3D string

//go:embed ascii/fontpack/hex.flf.gz
var fontHex string

//go:embed ascii/fontpack/hieroglyphs.flf.gz
var fontHieroglyphs string

//go:embed ascii/fontpack/hollywood.flf.gz
var fontHollywood string

//go:embed ascii/fontpack/horizontalleft.flf.gz
var fontHorizontalLeft string

//go:embed ascii/fontpack/horizontalright.flf.gz
var fontHorizontalRight string

//go:embed ascii/fontpack/icl1900.flf.gz
var fontICL1900 string

//go:embed ascii/fontpack/impossible.flf.gz
var fontImpossible string

//go:embed ascii/fontpack/invita.flf.gz
var fontInvita string

//go:embed ascii/fontpack/isometric1.flf.gz
var fontIsometric1 string

//go:embed ascii/fontpack/isometric2.flf.gz
var fontIsometric2 string

//go:embed ascii/fontpack/isometric3.flf.gz
var fontIsometric3 string

//go:embed ascii/fontpack/isometric4.flf.gz
var fontIsometric4 string

//go:embed ascii/fontpack/italic.flf.gz
var fontItalic string

//go:embed ascii/fontpack/ivrit.flf.gz
var fontIvrit string

//go:embed ascii/fontpack/jsblockletters.flf.gz
var fontJSBlockLetters string

//go:embed ascii/fontpack/jsbracketletters.flf.gz
var fontJSBracketLetters string

//go:embed ascii/fontpack/jscapitalcurves.flf.gz
var fontJSCapitalCurves string

//go:embed ascii/fontpack/jscursive.flf.gz
var fontJSCursive string

//go:embed ascii/fontpack/jsstickletters.flf.gz
var fontJSStickLetters string

//go:embed ascii/fontpack/jacky.flf.gz
var fontJacky string

//go:embed ascii/fontpack/jazmine.flf.gz
var fontJazmine string

//go:embed ascii/fontpack/jerusalem.flf.gz
var fontJerusalem string

//go:embed ascii/fontpack/katakana.flf.gz
var fontKatakana string

//go:embed ascii/fontpack/kban.flf.gz
var fontKban string

//go:embed ascii/fontpack/keyboard.flf.gz
var fontKeyboard string

//go:embed ascii/fontpack/knob.flf.gz
var fontKnob string

//go:embed ascii/fontpack/konto.flf.gz
var fontKonto string

//go:embed ascii/fontpack/kontoslant.flf.gz
var fontKontoSlant string

//go:embed ascii/fontpack/lcd.flf.gz
var fontLCD string

//go:embed ascii/fontpack/larry3d.flf.gz
var fontLarry3D string

//go:embed ascii/fontpack/larry3d2.flf.gz
var fontLarry3D2 string

//go:embed ascii/fontpack/lean.flf.gz
var fontLean string

//go:embed ascii/fontpack/letters.flf.gz
var fontLetters string

//go:embed ascii/fontpack/lildevil.flf.gz
var fontLilDevil string

//go:embed ascii/fontpack/lineblocks.flf.gz
var fontLineBlocks string

//go:embed ascii/fontpack/linux.flf.gz
var fontLinux string

//go:embed ascii/fontpack/lockergnome.flf.gz
var fontLockergnome string

//go:embed ascii/fontpack/madrid.flf.gz
var fontMadrid string

//go:embed ascii/fontpack/marquee.flf.gz
var fontMarquee string

//go:embed ascii/fontpack/maxfour.flf.gz
var fontMaxfour string

//go:embed ascii/fontpack/merlin1.flf.gz
var fontMerlin1 string

//go:embed ascii/fontpack/merlin2.flf.gz
var fontMerlin2 string

//go:embed ascii/fontpack/mike.flf.gz
var fontMike string

//go:embed ascii/fontpack/mini.flf.gz
var fontMini string

//go:embed ascii/fontpack/mirror.flf.gz
var fontMirror string

//go:embed ascii/fontpack/mnemonic.flf.gz
var fontMnemonic string

//go:embed ascii/fontpack/modular.flf.gz
var fontModular string

//go:embed ascii/fontpack/morse.flf.gz
var fontMorse string

//go:embed ascii/fontpack/morse2.flf.gz
var fontMorse2 string

//go:embed ascii/fontpack/moscow.flf.gz
var fontMoscow string

//go:embed ascii/fontpack/mshebrew210.flf.gz
var fontMshebrew210 string

//go:embed ascii/fontpack/muzzle.flf.gz
var fontMuzzle string

//go:embed ascii/fontpack/nscript.flf.gz
var fontNScript string

//go:embed ascii/fontpack/ntgreek.flf.gz
var fontNTGreek string

//go:embed ascii/fontpack/nvscript.flf.gz
var fontNVScript string

//go:embed ascii/fontpack/nancyj.flf.gz
var fontNancyj string

//go:embed ascii/fontpack/nancyjfancy.flf.gz
var fontNancyjFancy string

//go:embed ascii/fontpack/nancyjimproved.flf.gz
var fontNancyjImproved string

//go:embed ascii/fontpack/nancyjunderlined.flf.gz
var fontNancyjUnderlined string

//go:embed ascii/fontpack/nipples.flf.gz
var fontNipples string

//go:embed ascii/fontpack/o8.flf.gz
var fontO8 string

//go:embed ascii/fontpack/os2.flf.gz
var fontOS2 string

//go:embed ascii/fontpack/octal.flf.gz
var fontOctal string

//go:embed ascii/fontpack/ogre.flf.gz
var fontOgre string

//go:embed ascii/fontpack/oldbanner.flf.gz
var fontOldBanner string

//go:embed ascii/fontpack/patorjkhex.flf.gz
var fontPatorjkHeX string

//go:embed ascii/fontpack/patorjkscheese.flf.gz
var fontPatorjksCheese string

//go:embed ascii/fontpack/pawp.flf.gz
var fontPawp string

//go:embed ascii/fontpack/peaks.flf.gz
var fontPeaks string

//go:embed ascii/fontpack/peaksslant.flf.gz
var fontPeaksSlant string

//go:embed ascii/fontpack/pebbles.flf.gz
var fontPebbles string

//go:embed ascii/fontpack/pepper.flf.gz
var fontPepper string

//go:embed ascii/fontpack/poison.flf.gz
var fontPoison string

//go:embed ascii/fontpack/puffy.flf.gz
var fontPuffy string

//go:embed ascii/fontpack/puzzle.flf.gz
var fontPuzzle string

//go:embed ascii/fontpack/pyramid.flf.gz
var fontPyramid string

//go:embed ascii/fontpack/rammstein.flf.gz
var fontRammstein string

//go:embed ascii/fontpack/rectangles.flf.gz
var fontRectangles string

//go:embed ascii/fontpack/redphoenix.flf.gz
var fontRedPhoenix string

//go:embed ascii/fontpack/relief.flf.gz
var fontRelief string

//go:embed ascii/fontpack/relief2.flf.gz
var fontRelief2 string

//go:embed ascii/fontpack/rev.flf.gz
var fontRev string

//go:embed ascii/fontpack/reverse.flf.gz
var fontReverse string

//go:embed ascii/fontpack/roman.flf.gz
var fontRoman string

//go:embed ascii/fontpack/rot13.flf.gz
var fontRot13 string

//go:embed ascii/fontpack/rotated.flf.gz
var fontRotated string

//go:embed ascii/fontpack/rounded.flf.gz
var fontRounded string

//go:embed ascii/fontpack/rowancap.flf.gz
var fontRowanCap string

//go:embed ascii/fontpack/rozzo.flf.gz
var fontRozzo string

//go:embed ascii/fontpack/runic.flf.gz
var fontRunic string

//go:embed ascii/fontpack/runyc.flf.gz
var fontRunyc string

//go:embed ascii/fontpack/sblood.flf.gz
var fontSBlood string

//go:embed ascii/fontpack/slscript.flf.gz
var fontSLScript string

//go:embed ascii/fontpack/santaclara.flf.gz
var fontSantaClara string

//go:embed ascii/fontpack/script.flf.gz
var fontScript string

//go:embed ascii/fontpack/serifcap.flf.gz
var fontSerifcap string

//go:embed ascii/fontpack/shadow.flf.gz
var fontShadow string

//go:embed ascii/fontpack/shimrod.flf.gz
var fontShimrod string

//go:embed ascii/fontpack/short.flf.gz
var fontShort string

//go:embed ascii/fontpack/slant.flf.gz
var fontSlant string

//go:embed ascii/fontpack/slantrelief.flf.gz
var fontSlantRelief string

//go:embed ascii/fontpack/slide.flf.gz
var fontSlide string

//go:embed ascii/fontpack/small.flf.gz
var fontSmall string

//go:embed ascii/fontpack/smallcaps.flf.gz
var fontSmallCaps string

//go:embed ascii/fontpack/smallisometric1.flf.gz
var fontSmallIsometric1 string

//go:embed ascii/fontpack/smallkeyboard.flf.gz
var fontSmallKeyboard string

//go:embed ascii/fontpack/smallpoison.flf.gz
var fontSmallPoison string

//go:embed ascii/fontpack/smallscript.flf.gz
var fontSmallScript string

//go:embed ascii/fontpack/smallshadow.flf.gz
var fontSmallShadow string

//go:embed ascii/fontpack/smallslant.flf.gz
var fontSmallSlant string

//go:embed ascii/fontpack/smalltengwar.flf.gz
var fontSmallTengwar string

//go:embed ascii/fontpack/smisome1.flf.gz
var fontSmisome1 string

//go:embed ascii/fontpack/smkeyboard.flf.gz
var fontSmkeyboard string

//go:embed ascii/fontpack/smpoison.flf.gz
var fontSmpoison string

//go:embed ascii/fontpack/smscript.flf.gz
var fontSmscript string

//go:embed ascii/fontpack/smshadow.flf.gz
var fontSmshadow string

//go:embed ascii/fontpack/smslant.flf.gz
var fontSmslant string

//go:embed ascii/fontpack/smtengwar.flf.gz
var fontSmtengwar string

//go:embed ascii/fontpack/soft.flf.gz
var fontSoft string

//go:embed ascii/fontpack/speed.flf.gz
var fontSpeed string

//go:embed ascii/fontpack/spliff.flf.gz
var fontSpliff string

//go:embed ascii/fontpack/srelief.flf.gz
var fontSrelief string

//go:embed ascii/fontpack/stacey.flf.gz
var fontStacey string

//go:embed ascii/fontpack/stampate.flf.gz
var fontStampate string

//go:embed ascii/fontpack/stampatello.flf.gz
var fontStampatello string

//go:embed ascii/fontpack/standard.flf.gz
var fontStandard string

//go:embed ascii/fontpack/starstrips.flf.gz
var fontStarStrips string

//go:embed ascii/fontpack/starwars.flf.gz
var fontStarWars string

//go:embed ascii/fontpack/stellar.flf.gz
var fontStellar string

//go:embed ascii/fontpack/stforek.flf.gz
var fontStforek string

//go:embed ascii/fontpack/stickletters.flf.gz
var fontStickLetters string

//go:embed ascii/fontpack/stop.flf.gz
var fontStop string

//go:embed ascii/fontpack/straight.flf.gz
var fontStraight string

//go:embed ascii/fontpack/strongerthanall.flf.gz
var fontStrongerThanAll string

//go:embed ascii/fontpack/subzero.flf.gz
var fontSubZero string

//go:embed ascii/fontpack/swampland.flf.gz
var fontSwampLand string

//go:embed ascii/fontpack/swan.flf.gz
var fontSwan string

//go:embed ascii/fontpack/sweet.flf.gz
var fontSweet string

//go:embed ascii/fontpack/this.flf.gz
var fontTHIS string

//go:embed ascii/fontpack/tanja.flf.gz
var fontTanja string

//go:embed ascii/fontpack/tengwar.flf.gz
var fontTengwar string

//go:embed ascii/fontpack/term.flf.gz
var fontTerm string

//go:embed ascii/fontpack/test1.flf.gz
var fontTest1 string

//go:embed ascii/fontpack/theedge.flf.gz
var fontTheEdge string

//go:embed ascii/fontpack/thick.flf.gz
var fontThick string

//go:embed ascii/fontpack/thin.flf.gz
var fontThin string

//go:embed ascii/fontpack/thorned.flf.gz
var fontThorned string

//go:embed ascii/fontpack/threepoint.flf.gz
var fontThreePoint string

//go:embed ascii/fontpack/ticks.flf.gz
var fontTicks string

//go:embed ascii/fontpack/ticksslant.flf.gz
var fontTicksSlant string

//go:embed ascii/fontpack/tiles.flf.gz
var fontTiles string

//go:embed ascii/fontpack/tinkertoy.flf.gz
var fontTinkerToy string

//go:embed ascii/fontpack/tombstone.flf.gz
var fontTombstone string

//go:embed ascii/fontpack/train.flf.gz
var fontTrain string

//go:embed ascii/fontpack/trek.flf.gz
var fontTrek string

//go:embed ascii/fontpack/tsalagi.flf.gz
var fontTsalagi string

//go:embed ascii/fontpack/tubular.flf.gz
var fontTubular string

//go:embed ascii/fontpack/twisted.flf.gz
var fontTwisted string

//go:embed ascii/fontpack/twopoint.flf.gz
var fontTwoPoint string

//go:embed ascii/fontpack/usaflag.flf.gz
var fontUSAFlag string

//go:embed ascii/fontpack/univers.flf.gz
var fontUnivers string

//go:embed ascii/fontpack/varsity.flf.gz
var fontVarsity string

//go:embed ascii/fontpack/wavy.flf.gz
var fontWavy string

//go:embed ascii/fontpack/weird.flf.gz
var fontWeird string

//go:embed ascii/fontpack/wetletter.flf.gz
var fontWetLetter string

//go:embed ascii/fontpack/whimsy.flf.gz
var fontWhimsy string

//go:embed ascii/fontpack/wow.flf.gz
var fontWow string

var fontDefault = fontANSIShadow

var fontMap = map[string]string{
	"amc3line":          fontAMC3Line,
	"amc3liv1":          fontAMC3Liv1,
	"amcaaa01":          fontAMCAAA01,
	"amcneko":           fontAMCNeko,
	"amcrazor":          fontAMCRazor,
	"amcrazor2":         fontAMCRazor2,
	"amcslash":          fontAMCSlash,
	"amcslider":         fontAMCSlider,
	"amcthin":           fontAMCThin,
	"amctubes":          fontAMCTubes,
	"amcuntitled":       fontAMCUntitled,
	"ansiregular":       fontANSIRegular,
	"ansishadow":        fontANSIShadow,
	"asciinewroman":     fontASCIINewRoman,
	"acrobatic":         fontAcrobatic,
	"alligator":         fontAlligator,
	"alligator2":        fontAlligator2,
	"alligator3":        fontAlligator3,
	"alpha":             fontAlpha,
	"alphabet":          fontAlphabet,
	"amcrazo2":          fontAmcrazo2,
	"amcslder":          fontAmcslder,
	"amcun1":            fontAmcun1,
	"arrows":            fontArrows,
	"avatar":            fontAvatar,
	"b1ff":              fontB1FF,
	"banner":            fontBanner,
	"banner3":           fontBanner3,
	"banner3d":          fontBanner3D,
	"banner4":           fontBanner4,
	"barbwire":          fontBarbwire,
	"basic":             fontBasic,
	"bear":              fontBear,
	"bell":              fontBell,
	"benjamin":          fontBenjamin,
	"big":               fontBig,
	"bigchief":          fontBigChief,
	"bigmoneyne":        fontBigMoneyne,
	"bigmoneynw":        fontBigMoneynw,
	"bigmoneyse":        fontBigMoneyse,
	"bigmoneysw":        fontBigMoneysw,
	"bigfig":            fontBigfig,
	"binary":            fontBinary,
	"block":             fontBlock,
	"blocks":            fontBlocks,
	"bloody":            fontBloody,
	"bolger":            fontBolger,
	"braced":            fontBraced,
	"bright":            fontBright,
	"broadway":          fontBroadway,
	"broadwaykb":        fontBroadwayKB,
	"bubble":            fontBubble,
	"bulbhead":          fontBulbhead,
	"calgphy2":          fontCalgphy2,
	"caligraphy":        fontCaligraphy,
	"caligraphy2":       fontCaligraphy2,
	"calvins":           fontCalvinS,
	"catwalk":           fontCatwalk,
	"chiseled":          fontChiseled,
	"chunky":            fontChunky,
	"coinstak":          fontCoinstak,
	"cola":              fontCola,
	"colossal":          fontColossal,
	"computer":          fontComputer,
	"contessa":          fontContessa,
	"contrast":          fontContrast,
	"cosmic":            fontCosmic,
	"cosmike":           fontCosmike,
	"crawford":          fontCrawford,
	"crawford2":         fontCrawford2,
	"crazy":             fontCrazy,
	"cricket":           fontCricket,
	"cursive":           fontCursive,
	"cyberlarge":        fontCyberlarge,
	"cybermedium":       fontCybermedium,
	"cybersmall":        fontCybersmall,
	"cygnet":            fontCygnet,
	"danc4":             fontDANC4,
	"dosrebel":          fontDOSRebel,
	"dwhistled":         fontDWhistled,
	"dancingfont":       fontDancingFont,
	"decimal":           fontDecimal,
	"defleppard":        fontDefLeppard,
	"deltacorpspriest1": fontDeltaCorpsPriest1,
	"diamond":           fontDiamond,
	"dietcola":          fontDietCola,
	"digital":           fontDigital,
	"doh":               fontDoh,
	"doom":              fontDoom,
	"dotmatrix":         fontDotMatrix,
	"double":            fontDouble,
	"doubleshorts":      fontDoubleShorts,
	"drpepper":          fontDrPepper,
	"eftichess":         fontEftiChess,
	"eftifont":          fontEftiFont,
	"eftiitalic":        fontEftiItalic,
	"eftipiti":          fontEftiPiti,
	"eftirobot":         fontEftiRobot,
	"eftiwall":          fontEftiWall,
	"eftiwater":         fontEftiWater,
	"eftitalic":         fontEftitalic,
	"electronic":        fontElectronic,
	"elite":             fontElite,
	"epic":              fontEpic,
	"f1row":             fontF1Row,
	"f3d":               fontF3D,
	"f3dascii":          fontF3DASCII,
	"f3ddiagonal":       fontF3DDiagonal,
	"f3x5":              fontF3x5,
	"f4max":             fontF4Max,
	"f5lineoblique":     fontF5LineOblique,
	"fender":            fontFender,
	"filter":            fontFilter,
	"firefontk":         fontFireFontk,
	"firefonts":         fontFireFonts,
	"flipped":           fontFlipped,
	"flowerpower":       fontFlowerPower,
	"fourtops":          fontFourTops,
	"funface":           fontFunFace,
	"funfaces":          fontFunFaces,
	"fuzzy":             fontFuzzy,
	"georgi16":          fontGeorgi16,
	"georgia11":         fontGeorgia11,
	"ghost":             fontGhost,
	"ghoulish":          fontGhoulish,
	"glenyn":            fontGlenyn,
	"goofy":             fontGoofy,
	"gothic":            fontGothic,
	"graceful":          fontGraceful,
	"gradient":          fontGradient,
	"graffiti":          fontGraffiti,
	"greek":             fontGreek,
	"halfiwi":           fontHalfiwi,
	"henry3d":           fontHenry3D,
	"hex":               fontHex,
	"hieroglyphs":       fontHieroglyphs,
	"hollywood":         fontHollywood,
	"horizontalleft":    fontHorizontalLeft,
	"horizontalright":   fontHorizontalRight,
	"icl1900":           fontICL1900,
	"impossible":        fontImpossible,
	"invita":            fontInvita,
	"isometric1":        fontIsometric1,
	"isometric2":        fontIsometric2,
	"isometric3":        fontIsometric3,
	"isometric4":        fontIsometric4,
	"italic":            fontItalic,
	"ivrit":             fontIvrit,
	"jsblockletters":    fontJSBlockLetters,
	"jsbracketletters":  fontJSBracketLetters,
	"jscapitalcurves":   fontJSCapitalCurves,
	"jscursive":         fontJSCursive,
	"jsstickletters":    fontJSStickLetters,
	"jacky":             fontJacky,
	"jazmine":           fontJazmine,
	"jerusalem":         fontJerusalem,
	"katakana":          fontKatakana,
	"kban":              fontKban,
	"keyboard":          fontKeyboard,
	"knob":              fontKnob,
	"konto":             fontKonto,
	"kontoslant":        fontKontoSlant,
	"lcd":               fontLCD,
	"larry3d":           fontLarry3D,
	"larry3d2":          fontLarry3D2,
	"lean":              fontLean,
	"letters":           fontLetters,
	"lildevil":          fontLilDevil,
	"lineblocks":        fontLineBlocks,
	"linux":             fontLinux,
	"lockergnome":       fontLockergnome,
	"madrid":            fontMadrid,
	"marquee":           fontMarquee,
	"maxfour":           fontMaxfour,
	"merlin1":           fontMerlin1,
	"merlin2":           fontMerlin2,
	"mike":              fontMike,
	"mini":              fontMini,
	"mirror":            fontMirror,
	"mnemonic":          fontMnemonic,
	"modular":           fontModular,
	"morse":             fontMorse,
	"morse2":            fontMorse2,
	"moscow":            fontMoscow,
	"mshebrew210":       fontMshebrew210,
	"muzzle":            fontMuzzle,
	"nscript":           fontNScript,
	"ntgreek":           fontNTGreek,
	"nvscript":          fontNVScript,
	"nancyj":            fontNancyj,
	"nancyjfancy":       fontNancyjFancy,
	"nancyjimproved":    fontNancyjImproved,
	"nancyjunderlined":  fontNancyjUnderlined,
	"nipples":           fontNipples,
	"o8":                fontO8,
	"os2":               fontOS2,
	"octal":             fontOctal,
	"ogre":              fontOgre,
	"oldbanner":         fontOldBanner,
	"patorjkhex":        fontPatorjkHeX,
	"patorjkscheese":    fontPatorjksCheese,
	"pawp":              fontPawp,
	"peaks":             fontPeaks,
	"peaksslant":        fontPeaksSlant,
	"pebbles":           fontPebbles,
	"pepper":            fontPepper,
	"poison":            fontPoison,
	"puffy":             fontPuffy,
	"puzzle":            fontPuzzle,
	"pyramid":           fontPyramid,
	"rammstein":         fontRammstein,
	"rectangles":        fontRectangles,
	"redphoenix":        fontRedPhoenix,
	"relief":            fontRelief,
	"relief2":           fontRelief2,
	"rev":               fontRev,
	"reverse":           fontReverse,
	"roman":             fontRoman,
	"rot13":             fontRot13,
	"rotated":           fontRotated,
	"rounded":           fontRounded,
	"rowancap":          fontRowanCap,
	"rozzo":             fontRozzo,
	"runic":             fontRunic,
	"runyc":             fontRunyc,
	"sblood":            fontSBlood,
	"slscript":          fontSLScript,
	"santaclara":        fontSantaClara,
	"script":            fontScript,
	"serifcap":          fontSerifcap,
	"shadow":            fontShadow,
	"shimrod":           fontShimrod,
	"short":             fontShort,
	"slant":             fontSlant,
	"slantrelief":       fontSlantRelief,
	"slide":             fontSlide,
	"small":             fontSmall,
	"smallcaps":         fontSmallCaps,
	"smallisometric1":   fontSmallIsometric1,
	"smallkeyboard":     fontSmallKeyboard,
	"smallpoison":       fontSmallPoison,
	"smallscript":       fontSmallScript,
	"smallshadow":       fontSmallShadow,
	"smallslant":        fontSmallSlant,
	"smalltengwar":      fontSmallTengwar,
	"smisome1":          fontSmisome1,
	"smkeyboard":        fontSmkeyboard,
	"smpoison":          fontSmpoison,
	"smscript":          fontSmscript,
	"smshadow":          fontSmshadow,
	"smslant":           fontSmslant,
	"smtengwar":         fontSmtengwar,
	"soft":              fontSoft,
	"speed":             fontSpeed,
	"spliff":            fontSpliff,
	"srelief":           fontSrelief,
	"stacey":            fontStacey,
	"stampate":          fontStampate,
	"stampatello":       fontStampatello,
	"standard":          fontStandard,
	"starstrips":        fontStarStrips,
	"starwars":          fontStarWars,
	"stellar":           fontStellar,
	"stforek":           fontStforek,
	"stickletters":      fontStickLetters,
	"stop":              fontStop,
	"straight":          fontStraight,
	"strongerthanall":   fontStrongerThanAll,
	"subzero":           fontSubZero,
	"swampland":         fontSwampLand,
	"swan":              fontSwan,
	"sweet":             fontSweet,
	"this":              fontTHIS,
	"tanja":             fontTanja,
	"tengwar":           fontTengwar,
	"term":              fontTerm,
	"test1":             fontTest1,
	"theedge":           fontTheEdge,
	"thick":             fontThick,
	"thin":              fontThin,
	"thorned":           fontThorned,
	"threepoint":        fontThreePoint,
	"ticks":             fontTicks,
	"ticksslant":        fontTicksSlant,
	"tiles":             fontTiles,
	"tinkertoy":         fontTinkerToy,
	"tombstone":         fontTombstone,
	"train":             fontTrain,
	"trek":              fontTrek,
	"tsalagi":           fontTsalagi,
	"tubular":           fontTubular,
	"twisted":           fontTwisted,
	"twopoint":          fontTwoPoint,
	"usaflag":           fontUSAFlag,
	"univers":           fontUnivers,
	"varsity":           fontVarsity,
	"wavy":              fontWavy,
	"weird":             fontWeird,
	"wetletter":         fontWetLetter,
	"whimsy":            fontWhimsy,
	"wow":               fontWow,

	"default": fontANSIShadow,
}

func GetFonts() []string {
	var fonts []string
	for k := range fontMap {
		fonts = append(fonts, k)
	}
	return fonts
}

func GetFontName(f string) string {
	if _, ok := fontMap[strings.ToLower(f)]; ok {
		return f
	}
	fmt.Println("font not found, using default font")
	return GetFontName("default")
}

func loadFont(f string) (*font, error) {
	if f == "" {
		fmt.Print("font " + f + " not found, using default font")
		f = "default"
	}
	if val, ok := fontMap[strings.ToLower(f)]; ok {
		return ParseFlf(f, val)
	}
	return nil, fmt.Errorf("font not found")
}
