// Package ascii Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2023-08-24 11:44:30.661727 +1000 AEST m=+1.368358167
// using data from https://github.com/xero/figlet-fonts

//go:build !exclude

package ascii

import (
	_ "embed"
	"fmt"
	"strings"
)

func GetFonts() []string {
	var fonts []string
	for k := range fontMap {
		fonts = append(fonts, k)
	}
	return fonts
}

func MatchFont(name string) string {
	for k := range fontMap {
		if strings.Contains(k, name) {
			return k
		}
	}
	return "default"
}

var _fontcache map[string]font

func loadFont(name string) (*font, error) {
	if name == "" {
		fmt.Print("font " + name + " not found, using default font")
		name = "default"
	}
	if val, ok := fontMap[strings.ToLower(name)]; ok {
		return ParseFlf(name, val)
	}
	return nil, fmt.Errorf("font not found")
}

//go:embed fontpack/amc3line.flf.gz
var fontAMC3LineZip string
var FontAMC3Line = "amc3line"

//go:embed fontpack/amc3liv1.flf.gz
var fontAMC3Liv1Zip string
var FontAMC3Liv1 = "amc3liv1"

//go:embed fontpack/amcaaa01.flf.gz
var fontAMCAAA01Zip string
var FontAMCAAA01 = "amcaaa01"

//go:embed fontpack/amcneko.flf.gz
var fontAMCNekoZip string
var FontAMCNeko = "amcneko"

//go:embed fontpack/amcrazor.flf.gz
var fontAMCRazorZip string
var FontAMCRazor = "amcrazor"

//go:embed fontpack/amcrazor2.flf.gz
var fontAMCRazor2Zip string
var FontAMCRazor2 = "amcrazor2"

//go:embed fontpack/amcslash.flf.gz
var fontAMCSlashZip string
var FontAMCSlash = "amcslash"

//go:embed fontpack/amcslider.flf.gz
var fontAMCSliderZip string
var FontAMCSlider = "amcslider"

//go:embed fontpack/amcthin.flf.gz
var fontAMCThinZip string
var FontAMCThin = "amcthin"

//go:embed fontpack/amctubes.flf.gz
var fontAMCTubesZip string
var FontAMCTubes = "amctubes"

//go:embed fontpack/amcuntitled.flf.gz
var fontAMCUntitledZip string
var FontAMCUntitled = "amcuntitled"

//go:embed fontpack/ansiregular.flf.gz
var fontANSIRegularZip string
var FontANSIRegular = "ansiregular"

//go:embed fontpack/ansishadow.flf.gz
var fontANSIShadowZip string
var FontANSIShadow = "ansishadow"

//go:embed fontpack/asciinewroman.flf.gz
var fontASCIINewRomanZip string
var FontASCIINewRoman = "asciinewroman"

//go:embed fontpack/acrobatic.flf.gz
var fontAcrobaticZip string
var FontAcrobatic = "acrobatic"

//go:embed fontpack/alligator.flf.gz
var fontAlligatorZip string
var FontAlligator = "alligator"

//go:embed fontpack/alligator2.flf.gz
var fontAlligator2Zip string
var FontAlligator2 = "alligator2"

//go:embed fontpack/alligator3.flf.gz
var fontAlligator3Zip string
var FontAlligator3 = "alligator3"

//go:embed fontpack/alpha.flf.gz
var fontAlphaZip string
var FontAlpha = "alpha"

//go:embed fontpack/alphabet.flf.gz
var fontAlphabetZip string
var FontAlphabet = "alphabet"

//go:embed fontpack/amcrazo2.flf.gz
var fontAmcrazo2Zip string
var FontAmcrazo2 = "amcrazo2"

//go:embed fontpack/amcslder.flf.gz
var fontAmcslderZip string
var FontAmcslder = "amcslder"

//go:embed fontpack/amcun1.flf.gz
var fontAmcun1Zip string
var FontAmcun1 = "amcun1"

//go:embed fontpack/arrows.flf.gz
var fontArrowsZip string
var FontArrows = "arrows"

//go:embed fontpack/avatar.flf.gz
var fontAvatarZip string
var FontAvatar = "avatar"

//go:embed fontpack/b1ff.flf.gz
var fontB1FFZip string
var FontB1FF = "b1ff"

//go:embed fontpack/banner.flf.gz
var fontBannerZip string
var FontBanner = "banner"

//go:embed fontpack/banner3.flf.gz
var fontBanner3Zip string
var FontBanner3 = "banner3"

//go:embed fontpack/banner3d.flf.gz
var fontBanner3DZip string
var FontBanner3D = "banner3d"

//go:embed fontpack/banner4.flf.gz
var fontBanner4Zip string
var FontBanner4 = "banner4"

//go:embed fontpack/barbwire.flf.gz
var fontBarbwireZip string
var FontBarbwire = "barbwire"

//go:embed fontpack/basic.flf.gz
var fontBasicZip string
var FontBasic = "basic"

//go:embed fontpack/bear.flf.gz
var fontBearZip string
var FontBear = "bear"

//go:embed fontpack/bell.flf.gz
var fontBellZip string
var FontBell = "bell"

//go:embed fontpack/benjamin.flf.gz
var fontBenjaminZip string
var FontBenjamin = "benjamin"

//go:embed fontpack/big.flf.gz
var fontBigZip string
var FontBig = "big"

//go:embed fontpack/bigchief.flf.gz
var fontBigChiefZip string
var FontBigChief = "bigchief"

//go:embed fontpack/bigmoneyne.flf.gz
var fontBigMoneyneZip string
var FontBigMoneyne = "bigmoneyne"

//go:embed fontpack/bigmoneynw.flf.gz
var fontBigMoneynwZip string
var FontBigMoneynw = "bigmoneynw"

//go:embed fontpack/bigmoneyse.flf.gz
var fontBigMoneyseZip string
var FontBigMoneyse = "bigmoneyse"

//go:embed fontpack/bigmoneysw.flf.gz
var fontBigMoneyswZip string
var FontBigMoneysw = "bigmoneysw"

//go:embed fontpack/bigfig.flf.gz
var fontBigfigZip string
var FontBigfig = "bigfig"

//go:embed fontpack/binary.flf.gz
var fontBinaryZip string
var FontBinary = "binary"

//go:embed fontpack/block.flf.gz
var fontBlockZip string
var FontBlock = "block"

//go:embed fontpack/blocks.flf.gz
var fontBlocksZip string
var FontBlocks = "blocks"

//go:embed fontpack/bloody.flf.gz
var fontBloodyZip string
var FontBloody = "bloody"

//go:embed fontpack/bolger.flf.gz
var fontBolgerZip string
var FontBolger = "bolger"

//go:embed fontpack/braced.flf.gz
var fontBracedZip string
var FontBraced = "braced"

//go:embed fontpack/bright.flf.gz
var fontBrightZip string
var FontBright = "bright"

//go:embed fontpack/broadway.flf.gz
var fontBroadwayZip string
var FontBroadway = "broadway"

//go:embed fontpack/broadwaykb.flf.gz
var fontBroadwayKBZip string
var FontBroadwayKB = "broadwaykb"

//go:embed fontpack/bubble.flf.gz
var fontBubbleZip string
var FontBubble = "bubble"

//go:embed fontpack/bulbhead.flf.gz
var fontBulbheadZip string
var FontBulbhead = "bulbhead"

//go:embed fontpack/calgphy2.flf.gz
var fontCalgphy2Zip string
var FontCalgphy2 = "calgphy2"

//go:embed fontpack/caligraphy.flf.gz
var fontCaligraphyZip string
var FontCaligraphy = "caligraphy"

//go:embed fontpack/caligraphy2.flf.gz
var fontCaligraphy2Zip string
var FontCaligraphy2 = "caligraphy2"

//go:embed fontpack/calvins.flf.gz
var fontCalvinSZip string
var FontCalvinS = "calvins"

//go:embed fontpack/catwalk.flf.gz
var fontCatwalkZip string
var FontCatwalk = "catwalk"

//go:embed fontpack/chiseled.flf.gz
var fontChiseledZip string
var FontChiseled = "chiseled"

//go:embed fontpack/chunky.flf.gz
var fontChunkyZip string
var FontChunky = "chunky"

//go:embed fontpack/coinstak.flf.gz
var fontCoinstakZip string
var FontCoinstak = "coinstak"

//go:embed fontpack/cola.flf.gz
var fontColaZip string
var FontCola = "cola"

//go:embed fontpack/colossal.flf.gz
var fontColossalZip string
var FontColossal = "colossal"

//go:embed fontpack/computer.flf.gz
var fontComputerZip string
var FontComputer = "computer"

//go:embed fontpack/contessa.flf.gz
var fontContessaZip string
var FontContessa = "contessa"

//go:embed fontpack/contrast.flf.gz
var fontContrastZip string
var FontContrast = "contrast"

//go:embed fontpack/cosmic.flf.gz
var fontCosmicZip string
var FontCosmic = "cosmic"

//go:embed fontpack/cosmike.flf.gz
var fontCosmikeZip string
var FontCosmike = "cosmike"

//go:embed fontpack/crawford.flf.gz
var fontCrawfordZip string
var FontCrawford = "crawford"

//go:embed fontpack/crawford2.flf.gz
var fontCrawford2Zip string
var FontCrawford2 = "crawford2"

//go:embed fontpack/crazy.flf.gz
var fontCrazyZip string
var FontCrazy = "crazy"

//go:embed fontpack/cricket.flf.gz
var fontCricketZip string
var FontCricket = "cricket"

//go:embed fontpack/cursive.flf.gz
var fontCursiveZip string
var FontCursive = "cursive"

//go:embed fontpack/cyberlarge.flf.gz
var fontCyberlargeZip string
var FontCyberlarge = "cyberlarge"

//go:embed fontpack/cybermedium.flf.gz
var fontCybermediumZip string
var FontCybermedium = "cybermedium"

//go:embed fontpack/cybersmall.flf.gz
var fontCybersmallZip string
var FontCybersmall = "cybersmall"

//go:embed fontpack/cygnet.flf.gz
var fontCygnetZip string
var FontCygnet = "cygnet"

//go:embed fontpack/danc4.flf.gz
var fontDANC4Zip string
var FontDANC4 = "danc4"

//go:embed fontpack/dosrebel.flf.gz
var fontDOSRebelZip string
var FontDOSRebel = "dosrebel"

//go:embed fontpack/dwhistled.flf.gz
var fontDWhistledZip string
var FontDWhistled = "dwhistled"

//go:embed fontpack/dancingfont.flf.gz
var fontDancingFontZip string
var FontDancingFont = "dancingfont"

//go:embed fontpack/decimal.flf.gz
var fontDecimalZip string
var FontDecimal = "decimal"

//go:embed fontpack/defleppard.flf.gz
var fontDefLeppardZip string
var FontDefLeppard = "defleppard"

//go:embed fontpack/deltacorpspriest1.flf.gz
var fontDeltaCorpsPriest1Zip string
var FontDeltaCorpsPriest1 = "deltacorpspriest1"

//go:embed fontpack/diamond.flf.gz
var fontDiamondZip string
var FontDiamond = "diamond"

//go:embed fontpack/dietcola.flf.gz
var fontDietColaZip string
var FontDietCola = "dietcola"

//go:embed fontpack/digital.flf.gz
var fontDigitalZip string
var FontDigital = "digital"

//go:embed fontpack/doh.flf.gz
var fontDohZip string
var FontDoh = "doh"

//go:embed fontpack/doom.flf.gz
var fontDoomZip string
var FontDoom = "doom"

//go:embed fontpack/dotmatrix.flf.gz
var fontDotMatrixZip string
var FontDotMatrix = "dotmatrix"

//go:embed fontpack/double.flf.gz
var fontDoubleZip string
var FontDouble = "double"

//go:embed fontpack/doubleshorts.flf.gz
var fontDoubleShortsZip string
var FontDoubleShorts = "doubleshorts"

//go:embed fontpack/drpepper.flf.gz
var fontDrPepperZip string
var FontDrPepper = "drpepper"

//go:embed fontpack/eftichess.flf.gz
var fontEftiChessZip string
var FontEftiChess = "eftichess"

//go:embed fontpack/eftifont.flf.gz
var fontEftiFontZip string
var FontEftiFont = "eftifont"

//go:embed fontpack/eftiitalic.flf.gz
var fontEftiItalicZip string
var FontEftiItalic = "eftiitalic"

//go:embed fontpack/eftipiti.flf.gz
var fontEftiPitiZip string
var FontEftiPiti = "eftipiti"

//go:embed fontpack/eftirobot.flf.gz
var fontEftiRobotZip string
var FontEftiRobot = "eftirobot"

//go:embed fontpack/eftiwall.flf.gz
var fontEftiWallZip string
var FontEftiWall = "eftiwall"

//go:embed fontpack/eftiwater.flf.gz
var fontEftiWaterZip string
var FontEftiWater = "eftiwater"

//go:embed fontpack/eftitalic.flf.gz
var fontEftitalicZip string
var FontEftitalic = "eftitalic"

//go:embed fontpack/electronic.flf.gz
var fontElectronicZip string
var FontElectronic = "electronic"

//go:embed fontpack/elite.flf.gz
var fontEliteZip string
var FontElite = "elite"

//go:embed fontpack/epic.flf.gz
var fontEpicZip string
var FontEpic = "epic"

//go:embed fontpack/f1row.flf.gz
var fontF1RowZip string
var FontF1Row = "f1row"

//go:embed fontpack/f3d.flf.gz
var fontF3DZip string
var FontF3D = "f3d"

//go:embed fontpack/f3dascii.flf.gz
var fontF3DASCIIZip string
var FontF3DASCII = "f3dascii"

//go:embed fontpack/f3ddiagonal.flf.gz
var fontF3DDiagonalZip string
var FontF3DDiagonal = "f3ddiagonal"

//go:embed fontpack/f3x5.flf.gz
var fontF3x5Zip string
var FontF3x5 = "f3x5"

//go:embed fontpack/f4max.flf.gz
var fontF4MaxZip string
var FontF4Max = "f4max"

//go:embed fontpack/f5lineoblique.flf.gz
var fontF5LineObliqueZip string
var FontF5LineOblique = "f5lineoblique"

//go:embed fontpack/fender.flf.gz
var fontFenderZip string
var FontFender = "fender"

//go:embed fontpack/filter.flf.gz
var fontFilterZip string
var FontFilter = "filter"

//go:embed fontpack/firefontk.flf.gz
var fontFireFontkZip string
var FontFireFontk = "firefontk"

//go:embed fontpack/firefonts.flf.gz
var fontFireFontsZip string
var FontFireFonts = "firefonts"

//go:embed fontpack/flipped.flf.gz
var fontFlippedZip string
var FontFlipped = "flipped"

//go:embed fontpack/flowerpower.flf.gz
var fontFlowerPowerZip string
var FontFlowerPower = "flowerpower"

//go:embed fontpack/fourtops.flf.gz
var fontFourTopsZip string
var FontFourTops = "fourtops"

//go:embed fontpack/funface.flf.gz
var fontFunFaceZip string
var FontFunFace = "funface"

//go:embed fontpack/funfaces.flf.gz
var fontFunFacesZip string
var FontFunFaces = "funfaces"

//go:embed fontpack/fuzzy.flf.gz
var fontFuzzyZip string
var FontFuzzy = "fuzzy"

//go:embed fontpack/georgi16.flf.gz
var fontGeorgi16Zip string
var FontGeorgi16 = "georgi16"

//go:embed fontpack/georgia11.flf.gz
var fontGeorgia11Zip string
var FontGeorgia11 = "georgia11"

//go:embed fontpack/ghost.flf.gz
var fontGhostZip string
var FontGhost = "ghost"

//go:embed fontpack/ghoulish.flf.gz
var fontGhoulishZip string
var FontGhoulish = "ghoulish"

//go:embed fontpack/glenyn.flf.gz
var fontGlenynZip string
var FontGlenyn = "glenyn"

//go:embed fontpack/goofy.flf.gz
var fontGoofyZip string
var FontGoofy = "goofy"

//go:embed fontpack/gothic.flf.gz
var fontGothicZip string
var FontGothic = "gothic"

//go:embed fontpack/graceful.flf.gz
var fontGracefulZip string
var FontGraceful = "graceful"

//go:embed fontpack/gradient.flf.gz
var fontGradientZip string
var FontGradient = "gradient"

//go:embed fontpack/graffiti.flf.gz
var fontGraffitiZip string
var FontGraffiti = "graffiti"

//go:embed fontpack/greek.flf.gz
var fontGreekZip string
var FontGreek = "greek"

//go:embed fontpack/halfiwi.flf.gz
var fontHalfiwiZip string
var FontHalfiwi = "halfiwi"

//go:embed fontpack/henry3d.flf.gz
var fontHenry3DZip string
var FontHenry3D = "henry3d"

//go:embed fontpack/hex.flf.gz
var fontHexZip string
var FontHex = "hex"

//go:embed fontpack/hieroglyphs.flf.gz
var fontHieroglyphsZip string
var FontHieroglyphs = "hieroglyphs"

//go:embed fontpack/hollywood.flf.gz
var fontHollywoodZip string
var FontHollywood = "hollywood"

//go:embed fontpack/horizontalleft.flf.gz
var fontHorizontalLeftZip string
var FontHorizontalLeft = "horizontalleft"

//go:embed fontpack/horizontalright.flf.gz
var fontHorizontalRightZip string
var FontHorizontalRight = "horizontalright"

//go:embed fontpack/icl1900.flf.gz
var fontICL1900Zip string
var FontICL1900 = "icl1900"

//go:embed fontpack/impossible.flf.gz
var fontImpossibleZip string
var FontImpossible = "impossible"

//go:embed fontpack/invita.flf.gz
var fontInvitaZip string
var FontInvita = "invita"

//go:embed fontpack/isometric1.flf.gz
var fontIsometric1Zip string
var FontIsometric1 = "isometric1"

//go:embed fontpack/isometric2.flf.gz
var fontIsometric2Zip string
var FontIsometric2 = "isometric2"

//go:embed fontpack/isometric3.flf.gz
var fontIsometric3Zip string
var FontIsometric3 = "isometric3"

//go:embed fontpack/isometric4.flf.gz
var fontIsometric4Zip string
var FontIsometric4 = "isometric4"

//go:embed fontpack/italic.flf.gz
var fontItalicZip string
var FontItalic = "italic"

//go:embed fontpack/ivrit.flf.gz
var fontIvritZip string
var FontIvrit = "ivrit"

//go:embed fontpack/jsblockletters.flf.gz
var fontJSBlockLettersZip string
var FontJSBlockLetters = "jsblockletters"

//go:embed fontpack/jsbracketletters.flf.gz
var fontJSBracketLettersZip string
var FontJSBracketLetters = "jsbracketletters"

//go:embed fontpack/jscapitalcurves.flf.gz
var fontJSCapitalCurvesZip string
var FontJSCapitalCurves = "jscapitalcurves"

//go:embed fontpack/jscursive.flf.gz
var fontJSCursiveZip string
var FontJSCursive = "jscursive"

//go:embed fontpack/jsstickletters.flf.gz
var fontJSStickLettersZip string
var FontJSStickLetters = "jsstickletters"

//go:embed fontpack/jacky.flf.gz
var fontJackyZip string
var FontJacky = "jacky"

//go:embed fontpack/jazmine.flf.gz
var fontJazmineZip string
var FontJazmine = "jazmine"

//go:embed fontpack/jerusalem.flf.gz
var fontJerusalemZip string
var FontJerusalem = "jerusalem"

//go:embed fontpack/katakana.flf.gz
var fontKatakanaZip string
var FontKatakana = "katakana"

//go:embed fontpack/kban.flf.gz
var fontKbanZip string
var FontKban = "kban"

//go:embed fontpack/keyboard.flf.gz
var fontKeyboardZip string
var FontKeyboard = "keyboard"

//go:embed fontpack/knob.flf.gz
var fontKnobZip string
var FontKnob = "knob"

//go:embed fontpack/konto.flf.gz
var fontKontoZip string
var FontKonto = "konto"

//go:embed fontpack/kontoslant.flf.gz
var fontKontoSlantZip string
var FontKontoSlant = "kontoslant"

//go:embed fontpack/lcd.flf.gz
var fontLCDZip string
var FontLCD = "lcd"

//go:embed fontpack/larry3d.flf.gz
var fontLarry3DZip string
var FontLarry3D = "larry3d"

//go:embed fontpack/larry3d2.flf.gz
var fontLarry3D2Zip string
var FontLarry3D2 = "larry3d2"

//go:embed fontpack/lean.flf.gz
var fontLeanZip string
var FontLean = "lean"

//go:embed fontpack/letters.flf.gz
var fontLettersZip string
var FontLetters = "letters"

//go:embed fontpack/lildevil.flf.gz
var fontLilDevilZip string
var FontLilDevil = "lildevil"

//go:embed fontpack/lineblocks.flf.gz
var fontLineBlocksZip string
var FontLineBlocks = "lineblocks"

//go:embed fontpack/linux.flf.gz
var fontLinuxZip string
var FontLinux = "linux"

//go:embed fontpack/lockergnome.flf.gz
var fontLockergnomeZip string
var FontLockergnome = "lockergnome"

//go:embed fontpack/madrid.flf.gz
var fontMadridZip string
var FontMadrid = "madrid"

//go:embed fontpack/marquee.flf.gz
var fontMarqueeZip string
var FontMarquee = "marquee"

//go:embed fontpack/maxfour.flf.gz
var fontMaxfourZip string
var FontMaxfour = "maxfour"

//go:embed fontpack/merlin1.flf.gz
var fontMerlin1Zip string
var FontMerlin1 = "merlin1"

//go:embed fontpack/merlin2.flf.gz
var fontMerlin2Zip string
var FontMerlin2 = "merlin2"

//go:embed fontpack/mike.flf.gz
var fontMikeZip string
var FontMike = "mike"

//go:embed fontpack/mini.flf.gz
var fontMiniZip string
var FontMini = "mini"

//go:embed fontpack/mirror.flf.gz
var fontMirrorZip string
var FontMirror = "mirror"

//go:embed fontpack/mnemonic.flf.gz
var fontMnemonicZip string
var FontMnemonic = "mnemonic"

//go:embed fontpack/modular.flf.gz
var fontModularZip string
var FontModular = "modular"

//go:embed fontpack/morse.flf.gz
var fontMorseZip string
var FontMorse = "morse"

//go:embed fontpack/morse2.flf.gz
var fontMorse2Zip string
var FontMorse2 = "morse2"

//go:embed fontpack/moscow.flf.gz
var fontMoscowZip string
var FontMoscow = "moscow"

//go:embed fontpack/mshebrew210.flf.gz
var fontMshebrew210Zip string
var FontMshebrew210 = "mshebrew210"

//go:embed fontpack/muzzle.flf.gz
var fontMuzzleZip string
var FontMuzzle = "muzzle"

//go:embed fontpack/nscript.flf.gz
var fontNScriptZip string
var FontNScript = "nscript"

//go:embed fontpack/ntgreek.flf.gz
var fontNTGreekZip string
var FontNTGreek = "ntgreek"

//go:embed fontpack/nvscript.flf.gz
var fontNVScriptZip string
var FontNVScript = "nvscript"

//go:embed fontpack/nancyj.flf.gz
var fontNancyjZip string
var FontNancyj = "nancyj"

//go:embed fontpack/nancyjfancy.flf.gz
var fontNancyjFancyZip string
var FontNancyjFancy = "nancyjfancy"

//go:embed fontpack/nancyjimproved.flf.gz
var fontNancyjImprovedZip string
var FontNancyjImproved = "nancyjimproved"

//go:embed fontpack/nancyjunderlined.flf.gz
var fontNancyjUnderlinedZip string
var FontNancyjUnderlined = "nancyjunderlined"

//go:embed fontpack/nipples.flf.gz
var fontNipplesZip string
var FontNipples = "nipples"

//go:embed fontpack/o8.flf.gz
var fontO8Zip string
var FontO8 = "o8"

//go:embed fontpack/os2.flf.gz
var fontOS2Zip string
var FontOS2 = "os2"

//go:embed fontpack/octal.flf.gz
var fontOctalZip string
var FontOctal = "octal"

//go:embed fontpack/ogre.flf.gz
var fontOgreZip string
var FontOgre = "ogre"

//go:embed fontpack/oldbanner.flf.gz
var fontOldBannerZip string
var FontOldBanner = "oldbanner"

//go:embed fontpack/patorjkhex.flf.gz
var fontPatorjkHeXZip string
var FontPatorjkHeX = "patorjkhex"

//go:embed fontpack/patorjkscheese.flf.gz
var fontPatorjksCheeseZip string
var FontPatorjksCheese = "patorjkscheese"

//go:embed fontpack/pawp.flf.gz
var fontPawpZip string
var FontPawp = "pawp"

//go:embed fontpack/peaks.flf.gz
var fontPeaksZip string
var FontPeaks = "peaks"

//go:embed fontpack/peaksslant.flf.gz
var fontPeaksSlantZip string
var FontPeaksSlant = "peaksslant"

//go:embed fontpack/pebbles.flf.gz
var fontPebblesZip string
var FontPebbles = "pebbles"

//go:embed fontpack/pepper.flf.gz
var fontPepperZip string
var FontPepper = "pepper"

//go:embed fontpack/poison.flf.gz
var fontPoisonZip string
var FontPoison = "poison"

//go:embed fontpack/puffy.flf.gz
var fontPuffyZip string
var FontPuffy = "puffy"

//go:embed fontpack/puzzle.flf.gz
var fontPuzzleZip string
var FontPuzzle = "puzzle"

//go:embed fontpack/pyramid.flf.gz
var fontPyramidZip string
var FontPyramid = "pyramid"

//go:embed fontpack/rammstein.flf.gz
var fontRammsteinZip string
var FontRammstein = "rammstein"

//go:embed fontpack/rectangles.flf.gz
var fontRectanglesZip string
var FontRectangles = "rectangles"

//go:embed fontpack/redphoenix.flf.gz
var fontRedPhoenixZip string
var FontRedPhoenix = "redphoenix"

//go:embed fontpack/relief.flf.gz
var fontReliefZip string
var FontRelief = "relief"

//go:embed fontpack/relief2.flf.gz
var fontRelief2Zip string
var FontRelief2 = "relief2"

//go:embed fontpack/rev.flf.gz
var fontRevZip string
var FontRev = "rev"

//go:embed fontpack/reverse.flf.gz
var fontReverseZip string
var FontReverse = "reverse"

//go:embed fontpack/roman.flf.gz
var fontRomanZip string
var FontRoman = "roman"

//go:embed fontpack/rot13.flf.gz
var fontRot13Zip string
var FontRot13 = "rot13"

//go:embed fontpack/rotated.flf.gz
var fontRotatedZip string
var FontRotated = "rotated"

//go:embed fontpack/rounded.flf.gz
var fontRoundedZip string
var FontRounded = "rounded"

//go:embed fontpack/rowancap.flf.gz
var fontRowanCapZip string
var FontRowanCap = "rowancap"

//go:embed fontpack/rozzo.flf.gz
var fontRozzoZip string
var FontRozzo = "rozzo"

//go:embed fontpack/runic.flf.gz
var fontRunicZip string
var FontRunic = "runic"

//go:embed fontpack/runyc.flf.gz
var fontRunycZip string
var FontRunyc = "runyc"

//go:embed fontpack/sblood.flf.gz
var fontSBloodZip string
var FontSBlood = "sblood"

//go:embed fontpack/slscript.flf.gz
var fontSLScriptZip string
var FontSLScript = "slscript"

//go:embed fontpack/santaclara.flf.gz
var fontSantaClaraZip string
var FontSantaClara = "santaclara"

//go:embed fontpack/script.flf.gz
var fontScriptZip string
var FontScript = "script"

//go:embed fontpack/serifcap.flf.gz
var fontSerifcapZip string
var FontSerifcap = "serifcap"

//go:embed fontpack/shadow.flf.gz
var fontShadowZip string
var FontShadow = "shadow"

//go:embed fontpack/shimrod.flf.gz
var fontShimrodZip string
var FontShimrod = "shimrod"

//go:embed fontpack/short.flf.gz
var fontShortZip string
var FontShort = "short"

//go:embed fontpack/slant.flf.gz
var fontSlantZip string
var FontSlant = "slant"

//go:embed fontpack/slantrelief.flf.gz
var fontSlantReliefZip string
var FontSlantRelief = "slantrelief"

//go:embed fontpack/slide.flf.gz
var fontSlideZip string
var FontSlide = "slide"

//go:embed fontpack/small.flf.gz
var fontSmallZip string
var FontSmall = "small"

//go:embed fontpack/smallcaps.flf.gz
var fontSmallCapsZip string
var FontSmallCaps = "smallcaps"

//go:embed fontpack/smallisometric1.flf.gz
var fontSmallIsometric1Zip string
var FontSmallIsometric1 = "smallisometric1"

//go:embed fontpack/smallkeyboard.flf.gz
var fontSmallKeyboardZip string
var FontSmallKeyboard = "smallkeyboard"

//go:embed fontpack/smallpoison.flf.gz
var fontSmallPoisonZip string
var FontSmallPoison = "smallpoison"

//go:embed fontpack/smallscript.flf.gz
var fontSmallScriptZip string
var FontSmallScript = "smallscript"

//go:embed fontpack/smallshadow.flf.gz
var fontSmallShadowZip string
var FontSmallShadow = "smallshadow"

//go:embed fontpack/smallslant.flf.gz
var fontSmallSlantZip string
var FontSmallSlant = "smallslant"

//go:embed fontpack/smalltengwar.flf.gz
var fontSmallTengwarZip string
var FontSmallTengwar = "smalltengwar"

//go:embed fontpack/smisome1.flf.gz
var fontSmisome1Zip string
var FontSmisome1 = "smisome1"

//go:embed fontpack/smkeyboard.flf.gz
var fontSmkeyboardZip string
var FontSmkeyboard = "smkeyboard"

//go:embed fontpack/smpoison.flf.gz
var fontSmpoisonZip string
var FontSmpoison = "smpoison"

//go:embed fontpack/smscript.flf.gz
var fontSmscriptZip string
var FontSmscript = "smscript"

//go:embed fontpack/smshadow.flf.gz
var fontSmshadowZip string
var FontSmshadow = "smshadow"

//go:embed fontpack/smslant.flf.gz
var fontSmslantZip string
var FontSmslant = "smslant"

//go:embed fontpack/smtengwar.flf.gz
var fontSmtengwarZip string
var FontSmtengwar = "smtengwar"

//go:embed fontpack/soft.flf.gz
var fontSoftZip string
var FontSoft = "soft"

//go:embed fontpack/speed.flf.gz
var fontSpeedZip string
var FontSpeed = "speed"

//go:embed fontpack/spliff.flf.gz
var fontSpliffZip string
var FontSpliff = "spliff"

//go:embed fontpack/srelief.flf.gz
var fontSreliefZip string
var FontSrelief = "srelief"

//go:embed fontpack/stacey.flf.gz
var fontStaceyZip string
var FontStacey = "stacey"

//go:embed fontpack/stampate.flf.gz
var fontStampateZip string
var FontStampate = "stampate"

//go:embed fontpack/stampatello.flf.gz
var fontStampatelloZip string
var FontStampatello = "stampatello"

//go:embed fontpack/standard.flf.gz
var fontStandardZip string
var FontStandard = "standard"

//go:embed fontpack/starstrips.flf.gz
var fontStarStripsZip string
var FontStarStrips = "starstrips"

//go:embed fontpack/starwars.flf.gz
var fontStarWarsZip string
var FontStarWars = "starwars"

//go:embed fontpack/stellar.flf.gz
var fontStellarZip string
var FontStellar = "stellar"

//go:embed fontpack/stforek.flf.gz
var fontStforekZip string
var FontStforek = "stforek"

//go:embed fontpack/stickletters.flf.gz
var fontStickLettersZip string
var FontStickLetters = "stickletters"

//go:embed fontpack/stop.flf.gz
var fontStopZip string
var FontStop = "stop"

//go:embed fontpack/straight.flf.gz
var fontStraightZip string
var FontStraight = "straight"

//go:embed fontpack/strongerthanall.flf.gz
var fontStrongerThanAllZip string
var FontStrongerThanAll = "strongerthanall"

//go:embed fontpack/subzero.flf.gz
var fontSubZeroZip string
var FontSubZero = "subzero"

//go:embed fontpack/swampland.flf.gz
var fontSwampLandZip string
var FontSwampLand = "swampland"

//go:embed fontpack/swan.flf.gz
var fontSwanZip string
var FontSwan = "swan"

//go:embed fontpack/sweet.flf.gz
var fontSweetZip string
var FontSweet = "sweet"

//go:embed fontpack/this.flf.gz
var fontTHISZip string
var FontTHIS = "this"

//go:embed fontpack/tanja.flf.gz
var fontTanjaZip string
var FontTanja = "tanja"

//go:embed fontpack/tengwar.flf.gz
var fontTengwarZip string
var FontTengwar = "tengwar"

//go:embed fontpack/term.flf.gz
var fontTermZip string
var FontTerm = "term"

//go:embed fontpack/test1.flf.gz
var fontTest1Zip string
var FontTest1 = "test1"

//go:embed fontpack/theedge.flf.gz
var fontTheEdgeZip string
var FontTheEdge = "theedge"

//go:embed fontpack/thick.flf.gz
var fontThickZip string
var FontThick = "thick"

//go:embed fontpack/thin.flf.gz
var fontThinZip string
var FontThin = "thin"

//go:embed fontpack/thorned.flf.gz
var fontThornedZip string
var FontThorned = "thorned"

//go:embed fontpack/threepoint.flf.gz
var fontThreePointZip string
var FontThreePoint = "threepoint"

//go:embed fontpack/ticks.flf.gz
var fontTicksZip string
var FontTicks = "ticks"

//go:embed fontpack/ticksslant.flf.gz
var fontTicksSlantZip string
var FontTicksSlant = "ticksslant"

//go:embed fontpack/tiles.flf.gz
var fontTilesZip string
var FontTiles = "tiles"

//go:embed fontpack/tinkertoy.flf.gz
var fontTinkerToyZip string
var FontTinkerToy = "tinkertoy"

//go:embed fontpack/tombstone.flf.gz
var fontTombstoneZip string
var FontTombstone = "tombstone"

//go:embed fontpack/train.flf.gz
var fontTrainZip string
var FontTrain = "train"

//go:embed fontpack/trek.flf.gz
var fontTrekZip string
var FontTrek = "trek"

//go:embed fontpack/tsalagi.flf.gz
var fontTsalagiZip string
var FontTsalagi = "tsalagi"

//go:embed fontpack/tubular.flf.gz
var fontTubularZip string
var FontTubular = "tubular"

//go:embed fontpack/twisted.flf.gz
var fontTwistedZip string
var FontTwisted = "twisted"

//go:embed fontpack/twopoint.flf.gz
var fontTwoPointZip string
var FontTwoPoint = "twopoint"

//go:embed fontpack/usaflag.flf.gz
var fontUSAFlagZip string
var FontUSAFlag = "usaflag"

//go:embed fontpack/univers.flf.gz
var fontUniversZip string
var FontUnivers = "univers"

//go:embed fontpack/varsity.flf.gz
var fontVarsityZip string
var FontVarsity = "varsity"

//go:embed fontpack/wavy.flf.gz
var fontWavyZip string
var FontWavy = "wavy"

//go:embed fontpack/weird.flf.gz
var fontWeirdZip string
var FontWeird = "weird"

//go:embed fontpack/wetletter.flf.gz
var fontWetLetterZip string
var FontWetLetter = "wetletter"

//go:embed fontpack/whimsy.flf.gz
var fontWhimsyZip string
var FontWhimsy = "whimsy"

//go:embed fontpack/wow.flf.gz
var fontWowZip string
var FontWow = "wow"

var FontDefault = FontANSIShadow

var fontMap = map[string]string{
	"amc3line":          fontAMC3LineZip,
	"amc3liv1":          fontAMC3Liv1Zip,
	"amcaaa01":          fontAMCAAA01Zip,
	"amcneko":           fontAMCNekoZip,
	"amcrazor":          fontAMCRazorZip,
	"amcrazor2":         fontAMCRazor2Zip,
	"amcslash":          fontAMCSlashZip,
	"amcslider":         fontAMCSliderZip,
	"amcthin":           fontAMCThinZip,
	"amctubes":          fontAMCTubesZip,
	"amcuntitled":       fontAMCUntitledZip,
	"ansiregular":       fontANSIRegularZip,
	"ansishadow":        fontANSIShadowZip,
	"asciinewroman":     fontASCIINewRomanZip,
	"acrobatic":         fontAcrobaticZip,
	"alligator":         fontAlligatorZip,
	"alligator2":        fontAlligator2Zip,
	"alligator3":        fontAlligator3Zip,
	"alpha":             fontAlphaZip,
	"alphabet":          fontAlphabetZip,
	"amcrazo2":          fontAmcrazo2Zip,
	"amcslder":          fontAmcslderZip,
	"amcun1":            fontAmcun1Zip,
	"arrows":            fontArrowsZip,
	"avatar":            fontAvatarZip,
	"b1ff":              fontB1FFZip,
	"banner":            fontBannerZip,
	"banner3":           fontBanner3Zip,
	"banner3d":          fontBanner3DZip,
	"banner4":           fontBanner4Zip,
	"barbwire":          fontBarbwireZip,
	"basic":             fontBasicZip,
	"bear":              fontBearZip,
	"bell":              fontBellZip,
	"benjamin":          fontBenjaminZip,
	"big":               fontBigZip,
	"bigchief":          fontBigChiefZip,
	"bigmoneyne":        fontBigMoneyneZip,
	"bigmoneynw":        fontBigMoneynwZip,
	"bigmoneyse":        fontBigMoneyseZip,
	"bigmoneysw":        fontBigMoneyswZip,
	"bigfig":            fontBigfigZip,
	"binary":            fontBinaryZip,
	"block":             fontBlockZip,
	"blocks":            fontBlocksZip,
	"bloody":            fontBloodyZip,
	"bolger":            fontBolgerZip,
	"braced":            fontBracedZip,
	"bright":            fontBrightZip,
	"broadway":          fontBroadwayZip,
	"broadwaykb":        fontBroadwayKBZip,
	"bubble":            fontBubbleZip,
	"bulbhead":          fontBulbheadZip,
	"calgphy2":          fontCalgphy2Zip,
	"caligraphy":        fontCaligraphyZip,
	"caligraphy2":       fontCaligraphy2Zip,
	"calvins":           fontCalvinSZip,
	"catwalk":           fontCatwalkZip,
	"chiseled":          fontChiseledZip,
	"chunky":            fontChunkyZip,
	"coinstak":          fontCoinstakZip,
	"cola":              fontColaZip,
	"colossal":          fontColossalZip,
	"computer":          fontComputerZip,
	"contessa":          fontContessaZip,
	"contrast":          fontContrastZip,
	"cosmic":            fontCosmicZip,
	"cosmike":           fontCosmikeZip,
	"crawford":          fontCrawfordZip,
	"crawford2":         fontCrawford2Zip,
	"crazy":             fontCrazyZip,
	"cricket":           fontCricketZip,
	"cursive":           fontCursiveZip,
	"cyberlarge":        fontCyberlargeZip,
	"cybermedium":       fontCybermediumZip,
	"cybersmall":        fontCybersmallZip,
	"cygnet":            fontCygnetZip,
	"danc4":             fontDANC4Zip,
	"dosrebel":          fontDOSRebelZip,
	"dwhistled":         fontDWhistledZip,
	"dancingfont":       fontDancingFontZip,
	"decimal":           fontDecimalZip,
	"defleppard":        fontDefLeppardZip,
	"deltacorpspriest1": fontDeltaCorpsPriest1Zip,
	"diamond":           fontDiamondZip,
	"dietcola":          fontDietColaZip,
	"digital":           fontDigitalZip,
	"doh":               fontDohZip,
	"doom":              fontDoomZip,
	"dotmatrix":         fontDotMatrixZip,
	"double":            fontDoubleZip,
	"doubleshorts":      fontDoubleShortsZip,
	"drpepper":          fontDrPepperZip,
	"eftichess":         fontEftiChessZip,
	"eftifont":          fontEftiFontZip,
	"eftiitalic":        fontEftiItalicZip,
	"eftipiti":          fontEftiPitiZip,
	"eftirobot":         fontEftiRobotZip,
	"eftiwall":          fontEftiWallZip,
	"eftiwater":         fontEftiWaterZip,
	"eftitalic":         fontEftitalicZip,
	"electronic":        fontElectronicZip,
	"elite":             fontEliteZip,
	"epic":              fontEpicZip,
	"f1row":             fontF1RowZip,
	"f3d":               fontF3DZip,
	"f3dascii":          fontF3DASCIIZip,
	"f3ddiagonal":       fontF3DDiagonalZip,
	"f3x5":              fontF3x5Zip,
	"f4max":             fontF4MaxZip,
	"f5lineoblique":     fontF5LineObliqueZip,
	"fender":            fontFenderZip,
	"filter":            fontFilterZip,
	"firefontk":         fontFireFontkZip,
	"firefonts":         fontFireFontsZip,
	"flipped":           fontFlippedZip,
	"flowerpower":       fontFlowerPowerZip,
	"fourtops":          fontFourTopsZip,
	"funface":           fontFunFaceZip,
	"funfaces":          fontFunFacesZip,
	"fuzzy":             fontFuzzyZip,
	"georgi16":          fontGeorgi16Zip,
	"georgia11":         fontGeorgia11Zip,
	"ghost":             fontGhostZip,
	"ghoulish":          fontGhoulishZip,
	"glenyn":            fontGlenynZip,
	"goofy":             fontGoofyZip,
	"gothic":            fontGothicZip,
	"graceful":          fontGracefulZip,
	"gradient":          fontGradientZip,
	"graffiti":          fontGraffitiZip,
	"greek":             fontGreekZip,
	"halfiwi":           fontHalfiwiZip,
	"henry3d":           fontHenry3DZip,
	"hex":               fontHexZip,
	"hieroglyphs":       fontHieroglyphsZip,
	"hollywood":         fontHollywoodZip,
	"horizontalleft":    fontHorizontalLeftZip,
	"horizontalright":   fontHorizontalRightZip,
	"icl1900":           fontICL1900Zip,
	"impossible":        fontImpossibleZip,
	"invita":            fontInvitaZip,
	"isometric1":        fontIsometric1Zip,
	"isometric2":        fontIsometric2Zip,
	"isometric3":        fontIsometric3Zip,
	"isometric4":        fontIsometric4Zip,
	"italic":            fontItalicZip,
	"ivrit":             fontIvritZip,
	"jsblockletters":    fontJSBlockLettersZip,
	"jsbracketletters":  fontJSBracketLettersZip,
	"jscapitalcurves":   fontJSCapitalCurvesZip,
	"jscursive":         fontJSCursiveZip,
	"jsstickletters":    fontJSStickLettersZip,
	"jacky":             fontJackyZip,
	"jazmine":           fontJazmineZip,
	"jerusalem":         fontJerusalemZip,
	"katakana":          fontKatakanaZip,
	"kban":              fontKbanZip,
	"keyboard":          fontKeyboardZip,
	"knob":              fontKnobZip,
	"konto":             fontKontoZip,
	"kontoslant":        fontKontoSlantZip,
	"lcd":               fontLCDZip,
	"larry3d":           fontLarry3DZip,
	"larry3d2":          fontLarry3D2Zip,
	"lean":              fontLeanZip,
	"letters":           fontLettersZip,
	"lildevil":          fontLilDevilZip,
	"lineblocks":        fontLineBlocksZip,
	"linux":             fontLinuxZip,
	"lockergnome":       fontLockergnomeZip,
	"madrid":            fontMadridZip,
	"marquee":           fontMarqueeZip,
	"maxfour":           fontMaxfourZip,
	"merlin1":           fontMerlin1Zip,
	"merlin2":           fontMerlin2Zip,
	"mike":              fontMikeZip,
	"mini":              fontMiniZip,
	"mirror":            fontMirrorZip,
	"mnemonic":          fontMnemonicZip,
	"modular":           fontModularZip,
	"morse":             fontMorseZip,
	"morse2":            fontMorse2Zip,
	"moscow":            fontMoscowZip,
	"mshebrew210":       fontMshebrew210Zip,
	"muzzle":            fontMuzzleZip,
	"nscript":           fontNScriptZip,
	"ntgreek":           fontNTGreekZip,
	"nvscript":          fontNVScriptZip,
	"nancyj":            fontNancyjZip,
	"nancyjfancy":       fontNancyjFancyZip,
	"nancyjimproved":    fontNancyjImprovedZip,
	"nancyjunderlined":  fontNancyjUnderlinedZip,
	"nipples":           fontNipplesZip,
	"o8":                fontO8Zip,
	"os2":               fontOS2Zip,
	"octal":             fontOctalZip,
	"ogre":              fontOgreZip,
	"oldbanner":         fontOldBannerZip,
	"patorjkhex":        fontPatorjkHeXZip,
	"patorjkscheese":    fontPatorjksCheeseZip,
	"pawp":              fontPawpZip,
	"peaks":             fontPeaksZip,
	"peaksslant":        fontPeaksSlantZip,
	"pebbles":           fontPebblesZip,
	"pepper":            fontPepperZip,
	"poison":            fontPoisonZip,
	"puffy":             fontPuffyZip,
	"puzzle":            fontPuzzleZip,
	"pyramid":           fontPyramidZip,
	"rammstein":         fontRammsteinZip,
	"rectangles":        fontRectanglesZip,
	"redphoenix":        fontRedPhoenixZip,
	"relief":            fontReliefZip,
	"relief2":           fontRelief2Zip,
	"rev":               fontRevZip,
	"reverse":           fontReverseZip,
	"roman":             fontRomanZip,
	"rot13":             fontRot13Zip,
	"rotated":           fontRotatedZip,
	"rounded":           fontRoundedZip,
	"rowancap":          fontRowanCapZip,
	"rozzo":             fontRozzoZip,
	"runic":             fontRunicZip,
	"runyc":             fontRunycZip,
	"sblood":            fontSBloodZip,
	"slscript":          fontSLScriptZip,
	"santaclara":        fontSantaClaraZip,
	"script":            fontScriptZip,
	"serifcap":          fontSerifcapZip,
	"shadow":            fontShadowZip,
	"shimrod":           fontShimrodZip,
	"short":             fontShortZip,
	"slant":             fontSlantZip,
	"slantrelief":       fontSlantReliefZip,
	"slide":             fontSlideZip,
	"small":             fontSmallZip,
	"smallcaps":         fontSmallCapsZip,
	"smallisometric1":   fontSmallIsometric1Zip,
	"smallkeyboard":     fontSmallKeyboardZip,
	"smallpoison":       fontSmallPoisonZip,
	"smallscript":       fontSmallScriptZip,
	"smallshadow":       fontSmallShadowZip,
	"smallslant":        fontSmallSlantZip,
	"smalltengwar":      fontSmallTengwarZip,
	"smisome1":          fontSmisome1Zip,
	"smkeyboard":        fontSmkeyboardZip,
	"smpoison":          fontSmpoisonZip,
	"smscript":          fontSmscriptZip,
	"smshadow":          fontSmshadowZip,
	"smslant":           fontSmslantZip,
	"smtengwar":         fontSmtengwarZip,
	"soft":              fontSoftZip,
	"speed":             fontSpeedZip,
	"spliff":            fontSpliffZip,
	"srelief":           fontSreliefZip,
	"stacey":            fontStaceyZip,
	"stampate":          fontStampateZip,
	"stampatello":       fontStampatelloZip,
	"standard":          fontStandardZip,
	"starstrips":        fontStarStripsZip,
	"starwars":          fontStarWarsZip,
	"stellar":           fontStellarZip,
	"stforek":           fontStforekZip,
	"stickletters":      fontStickLettersZip,
	"stop":              fontStopZip,
	"straight":          fontStraightZip,
	"strongerthanall":   fontStrongerThanAllZip,
	"subzero":           fontSubZeroZip,
	"swampland":         fontSwampLandZip,
	"swan":              fontSwanZip,
	"sweet":             fontSweetZip,
	"this":              fontTHISZip,
	"tanja":             fontTanjaZip,
	"tengwar":           fontTengwarZip,
	"term":              fontTermZip,
	"test1":             fontTest1Zip,
	"theedge":           fontTheEdgeZip,
	"thick":             fontThickZip,
	"thin":              fontThinZip,
	"thorned":           fontThornedZip,
	"threepoint":        fontThreePointZip,
	"ticks":             fontTicksZip,
	"ticksslant":        fontTicksSlantZip,
	"tiles":             fontTilesZip,
	"tinkertoy":         fontTinkerToyZip,
	"tombstone":         fontTombstoneZip,
	"train":             fontTrainZip,
	"trek":              fontTrekZip,
	"tsalagi":           fontTsalagiZip,
	"tubular":           fontTubularZip,
	"twisted":           fontTwistedZip,
	"twopoint":          fontTwoPointZip,
	"usaflag":           fontUSAFlagZip,
	"univers":           fontUniversZip,
	"varsity":           fontVarsityZip,
	"wavy":              fontWavyZip,
	"weird":             fontWeirdZip,
	"wetletter":         fontWetLetterZip,
	"whimsy":            fontWhimsyZip,
	"wow":               fontWowZip,

	"default": fontANSIShadowZip,
}
